import subprocess
import os
import sys
from pathlib import Path

import re
import time
import platform
import shutil
from dataclasses import dataclass
from typing import Optional
from AutoREACTER.input_parser import SimulationSetup
from AutoREACTER.reaction_preparation.lunar_client.locate_lunar import get_LUNAR_loc
from AutoREACTER.reaction_preparation.reaction_processor.prepare_reactions import ReactionMetadata

@dataclass(slots=True)
class DataFiles:
    data_files: dict[str, Path]  # Mapping of data molecule tags to their merged .data file paths
    force_field_data: Path  # Path to the combined force field parameter file generated by bond_react_merge

@dataclass(slots=True)
class MoleculeFiles:
    molecule_files: dict[str, Path]  # Mapping of molecule tags to their .mol file paths

@dataclass(slots=True)
class TemplateFiles:
    reaction_id: Optional[int]
    pre_reaction_files: dict[str, Path]  # Mapping of pre-reaction tags to their .lmpmol file paths
    post_reaction_files: dict[str, Path]  # Mapping of post-reaction tags to their .lmpmol file paths

@dataclass(slots=True)
class LunarFiles:
    data_files: list[DataFiles]  # Mapping of data molecule tags to their merged .data file paths
    molecule_files: list[MoleculeFiles]  # Mapping of molecule tags to their .mol file paths
    template_files: list[TemplateFiles]  # Mapping of reaction tags to their pre/post .lmpmol file paths

@dataclass(slots=True)
class AtomTypingResult:
    id : str  # Identifier for the molecule (e.g., "data1", "pre1", "post1")
    molecule : bool  # True if this is a molecule file, False if it's a template file
    typed_data_file: Path  # Path to the generated typed .data file
    nta_file: Path # Path to the generated .nta file

@dataclass(slots=True)
class All2LMPResult:
    id : str  # Identifier for the molecule (e.g., "data1", "pre1", "post1")
    molecule : bool  # True if this is a molecule file, False if it's a template file
    all2lmp_data_file: Path  # Path to the generated LAMMPS .data file

# Get current working directory
class LunarAPIWrapper:
    def __init__(self, cache_dir: Path):
        self.cache_dir = Path(cache_dir/ "lunar")
        self.LUNAR_LOCATION = get_LUNAR_loc(use_gui=False)
        self.atom_typing_py = os.path.join(self.LUNAR_LOCATION, "atom_typing.py")
        self.all2lmp_py = os.path.join(self.LUNAR_LOCATION, "all2lmp.py")
        self.bond_react_merge_py = os.path.join(self.LUNAR_LOCATION, "bond_react_merge.py")
        self._loading_screen("LUNAR API Wrapper Initialization")
        os.makedirs(self.cache_dir, exist_ok=True)
        LUNAR_CACHE_DIR = os.environ.get(
            "LUNAR_CACHE_DIR",
            self.cache_dir
        )
        self.cache_atom_typing = os.path.join(LUNAR_CACHE_DIR, "atom_typing")
        self.cache_all2lmp = os.path.join(LUNAR_CACHE_DIR, "all2lmp")
        self.cache_bond_react_merge = os.path.join(LUNAR_CACHE_DIR, "bond_react_merge")
        
        for p in (self.cache_dir, self.cache_atom_typing, self.cache_all2lmp, self.cache_bond_react_merge):
            os.makedirs(p, exist_ok=True)


    def _is_wsl(self) -> bool:
        return ("microsoft" in platform.release().lower()) or ("WSL_INTEROP" in os.environ)

    def _normalize_path(self, p: str | Path) -> str:
        p = str(p).strip().strip('"').strip("'")

        # normalize separators for parsing
        p = p.replace("\\", "/")

        # 1) WSL host: Windows drive path -> /mnt/<drive>/
        if self._is_wsl():
            m = re.match(r"^([A-Za-z]):/(.*)$", p)
            if m:
                drive = m.group(1).lower()
                rest = m.group(2)
                return f"/mnt/{drive}/{rest}"
            # already POSIX-ish on WSL
            return os.path.normpath(p)

        host = platform.system().lower()

        # 2) Windows host: /mnt/<drive>/... -> <DRIVE>:\...
        if host == "windows":
            m = re.match(r"^/?mnt/([A-Za-z])/(.*)$", p)
            if m:
                drive = m.group(1).upper()
                rest = m.group(2).replace("/", "\\")
                return f"{drive}:\\{rest}"
            # otherwise treat as Windows-ish path string
            return os.path.normpath(p.replace("/", "\\"))

        # 3) POSIX host (Linux/macOS, not WSL): keep POSIX
        return os.path.normpath(p)

    def _move_merge_outputs(src_dir: Path, dst_dir: Path):
        src_dir = Path(src_dir)
        dst_dir = Path(dst_dir)
        dst_dir.mkdir(parents=True, exist_ok=True)

        for pattern in ("*_merged.data", "*_merged.lmpmol", "force_field.data", "log.lammps", "*.log"):
            for f in src_dir.glob(pattern):
                shutil.move(str(f), str(dst_dir / f.name))

    def _loading_screen(name: str = "LUNAR") -> None:
        """
        Display an ASCII art banner with a loading spinner animation.
        
        This function provides visual feedback to users during long-running operations.
        
        Args:
            name (str): The name to display in the loading message. Defaults to "LUNAR".
        
        Returns:
            None
        """
        # ASCII art banner for LUNAR
        banner = r"""
        █████       █████  █████ ██████   █████   █████████   ███████████  
        ░░███       ░░███  ░░███ ░░██████ ░░███   ███░░░░░███ ░░███░░░░░███ 
        ░███        ░███   ░███  ░███░███ ░███  ░███    ░███  ░███    ░███ 
        ░███        ░███   ░███  ░███░░███░███  ░███████████  ░██████████  
        ░███        ░███   ░███  ░███ ░░██████  ░███░░░░░███  ░███░░░░░███ 
        ░███      █ ░███   ░███  ░███  ░░█████  ░███    ░███  ░███    ░███ 
        ███████████ ░░████████   █████  ░░█████ █████   █████ █████   █████
        ░░░░░░░░░░░   ░░░░░░░░   ░░░░░    ░░░░░ ░░░░░   ░░░░░ ░░░░░   ░░░░░ 
        """
        
        # Display the banner
        print(banner)
        print(f"Loading {name} ", end="", flush=True)

        # Loading animation characters
        animation = ["-", "\\", "|", "/"]
        
        # Run animation for 10 cycles
        for i in range(10):
            time.sleep(0.1)
            # Write backspace and next animation character
            sys.stdout.write("\b" + animation[i % len(animation)])
            sys.stdout.flush()
        
        print("\nReady!")


    def _get_ending_integer(s: str) -> int | None:
        """
        Extract and convert the trailing integer from a string.
        
        This function is useful for parsing reaction numbers from filenames
        (e.g., extracting "1" from "pre1" or "post1").
        
        Args:
            s (str): Input string that may end with an integer.
        
        Returns:
            int | None: The integer found at the end of the string, 
                    or None if no integer is found.
        
        Example:
            >>> get_ending_integer("pre1")
            1
            >>> get_ending_integer("data2")
            2
            >>> get_ending_integer("molecule")
            None
        """
        # Regular expression pattern to match one or more digits at the end of the string
        # r'\d+$' matches digits (\d+) at the end ($) of the string
        match = re.search(r'\d+$', s)
        
        if match:
            # Extract the matched substring and convert to integer
            return int(match.group())
        else:
            # No integer found at the end of the string
            return None
    

    def _run_LUNAR_atom_typing( self, 
                                updated_inputs: SimulationSetup,
                                prepared_reactions: list[ReactionMetadata],
                                force_field: str
                                ) -> tuple[SimulationSetup, list[ReactionMetadata]]:
        """
        Run LUNAR atom typing on a set of molecule files.
        
        This function assigns atom types to molecules using the PCFF-IFF force field
        and generates typed data files and NTA (Neighbor Table Analysis) files.
        
        Args:
            molecule_files (dict[str, Path]): Dictionary mapping molecule names to 
                                            their file paths. Files should be in 
                                            .mol format.
        
        Returns:
            dict[str, list[Path]]: Dictionary mapping molecule names to a list of 
                                two Path objects:
                                - [0]: Typed data file (.data)
                                - [1]: NTA file (.nta)
        
        Note:
            Uses the following LUNAR atom_typing.py command:
            python3 atom_typing.py -topo <file.mol> -dir <cache_dir> -ff PCFF-IFF 
                -del-method mass -del-crit 0
        """
        atom_typing_result = []

        def run_atom_typing_command(mol_file: Path, output_dir: Path):
            subprocess.run([
                sys.executable,          # Use the current Python interpreter
                self.atom_typing_py,              # Path to atom_typing.py script
                '-topo', str(mol_file), # Input molecule file
                '-dir', str(output_dir),  # Output directory for typed files
                '-ff', force_field,      # Force field to use (e.g., PCFF-IFF)
                '-del-method', 'mass',   # Deletion method for byproducts
                '-del-crit', '0'        # Deletion criterion threshold
            ], check=True)  # Raise an exception if the command fails

        # Process each molecule file
        monomer_entries = updated_inputs.monomers
        for entry in monomer_entries:
            # Construct and execute the atom typing command
            # Command format: python atom_typing.py -topo <file> -dir <cache> -ff PCFF-IFF -del-method mass -del-crit 0
            run_atom_typing_command(entry.molecule_3Dmol_path, self.cache_atom_typing)
            
            # Store paths to generated files
            # LUNAR generates two files: <stem>_typed.data and <stem>_typed.nta
            atom_typing_result.append(
                AtomTypingResult(
                    id=entry.data_id,
                    molecule=True,
                    typed_data_file=Path(self.cache_atom_typing) / f"{entry.data_id}_typed.data",
                    nta_file=Path(self.cache_atom_typing) / f"{entry.data_id}_typed.nta"
                )
            )

            time.sleep(0.1)  # Ensure all files are written before returning
                
        for reaction in prepared_reactions:
            for mol_path, label in [
                (reaction.reactants_3Dmol_path, "pre"),
                (reaction.products_3Dmol_path, "post"),
            ]:
                output_dir = Path(self.cache_atom_typing) / f"{label}_{reaction.reaction_id}"
                output_dir.mkdir(parents=True, exist_ok=True)

                run_atom_typing_command(mol_path, output_dir)

                typed_file = output_dir / f"{mol_path.stem}_typed.data"
                nta_file = output_dir / f"{mol_path.stem}_typed.nta"

                atom_typing_result.append(
                    AtomTypingResult(
                        id=f"{label}_{reaction.reaction_id}",
                        typed_data_file=typed_file,
                        nta_file=nta_file,
                        molecule=True
                    )
                )
                time.sleep(0.1)  # Ensure all files are written before returning

        for files in atom_typing_result:
            for path in [files.typed_data_file, files.nta_file]:
                if path.is_file():
                    print(f"[LUNAR bond_react_merge] Generated file for {files.id} at: {path}")
                else:             
                    raise FileNotFoundError(
                        typed_data_file=Path(self.cache_atom_typing) / f"{path.stem}_typed.data",
                        nta_file=Path(self.cache_atom_typing) / f"{path.stem}_typed.nta"
                    )
                            
        return atom_typing_result
    


    def _frc_file_for_force_field(self, force_field: str) -> str:
        base = Path(self.LUNAR_LOCATION) / "frc_files"

        paths = {
            "PCFF-IFF": base / "pcff_interface_v1_6mBN.frc",
            "PCFF": base / "pcff.frc",
            "Compass": base / "compass_published.frc",
            "CVFF-IFF": base / "cvff_aug.frc",
            "CVFF": base / "cvff.frc",
            "DRIEDING": base / "all2lmp_dreiding.frc",
        }

        if paths[force_field].is_file():
            return str(paths[force_field])
        else:
            raise ValueError(f"File not found for force field {force_field}. Please redownload LUNAR from https://github.com/CMMRLab/LUNAR")


    def _run_LUNAR_all2lmp(self, atom_typing_result: list[AtomTypingResult], force_field: str) -> list[All2LMPResult]:
        """
        Convert typed molecule files to LAMMPS data format using LUNAR's all2lmp utility.
        
        This function takes the typed data and NTA files and converts them to 
        LAMMPS-readable data files with force field parameters.
        
        Args:
            molecule_files_typed (dict[str, list[Path]]): Dictionary mapping molecule 
                                                        names to a list of two Paths:
                                                        [data_file, nta_file]
        
        Returns:
            dict[str, str]: Dictionary mapping molecule names to the generated 
                        LAMMPS data filenames (without full path).
        
        Note:
            Uses the following LUNAR all2lmp.py command:
            python3 all2lmp.py -topo <data_file> -nta <nta_file> -frc <frc_file> 
                -dir <cache_dir>
        """
        # Sometimes LUNAR can't identify the .frc file location automatically,
        # so we provide the full path to the force field file
        frc_file = self._frc_file_for_force_field(force_field)  # Adjust force field as needed
        
        all2lmp_results = []

        # Process each typed molecule
        for entry in atom_typing_result:
            name = entry.data_id
            data_file = entry.typed_data_file
            nta_file = entry.nta_file
            molecule = entry.molecule

            # Construct and execute the all2lmp converion command
            # Command format: python all2lmp.py -topo <dsata> -nta <nta> -frc <frc> -dir <cache>
            subprocess.run([
                sys.executable,          # Use the current Python interpreter
                self.all2lmp_py,              # Path to all2lmp.py script
                '-topo', str(data_file), # Typed data file
                '-nta', str(nta_file),   # NTA file
                '-frc', frc_file,        # Force field file
                '-dir', self.cache_all2lmp  # Output directory
            ])
            
            # Store the generated LAMMPS data filename
            # LUNAR generates: <stem>_IFF.data (e.g., data1_typed_IFF.data)
            all2lmp_results.append(All2LMPResult(
                id=name,
                all2lmp_data_file= f"{name}_IFF.data",
                molecule=molecule
            ))

        time.sleep(0.1)  # Ensure all files are written before returning
        for result in all2lmp_results:
            # Construct full path to the generated file
            path = Path(self.cache_all2lmp) / result.all2lmp_data_file
            if Path(path).is_file():
                print(f"[LUNAR bond_react_merge] Generated file for {result.id} at: {path}")
            else:
                raise FileNotFoundError(
                    f"Expected output file for {result.id} not found at {path}"
                )
        return all2lmp_results


    def _write_bond_react_merge_input(self,
        molecule_files_all2lmp: list[All2LMPResult],
    ) -> Path:
        """Generate the merge input file used by Bond React Merge binaries.

        Args:
            molecule_files_all2lmp: Mapping of file tags to their corresponding LAMMPS filenames.
            cache_bond_react_merge: Target directory where the merge input and merge results will be written.
            cache_all2lmp: Directory that holds the generated LAMMPS files referenced in the merge list.

        Returns:
            Path to the directory containing the newly written merge_input.txt file.
        """
        # Ensure the provided paths are normalized (resolving redundant separators, symlinks, etc.).
        cache_bond_react_merge_normalized = Path(self._normalize_path(self.cache_bond_react_merge))
        cache_all2lmp = Path(self._normalize_path(self.cache_all2lmp))

        # Create the output directory if it does not already exist.
        os.makedirs(cache_bond_react_merge_normalized, exist_ok=True)
        # Initialize the merge input file content with header comments and column titles.
        merge_files = f"""# anything following the "#" character will be ignored

    {"# file-tag":<10}{"filename":<150}{"comment (required)"}
    """

        # Append one line per molecule file describing the tag, absolute path, and reason comment.
        for result in molecule_files_all2lmp:
            name = result.id
            lammps_file = result.all2lmp_data_file
            if result.molecule:
                comment = "# This datafile will have all coeffs in it"
            else:
                rxn_number = self._get_ending_integer(name)
                comment = f"# for rxn_{rxn_number}"

            full_file = self._normalize_path(Path(cache_all2lmp) / lammps_file)
            merge_files += f"{name:<10}{full_file:<150}{comment}\n"

        # Specify where the merge outputs should be written to within the merge_input file.
        merge_files += f"""
    # Specify the parent_directory of where to write results (optional)
    """
        # Write the complete merge input text to the target file.
        with open(cache_bond_react_merge_normalized / "merge_input.txt", "w") as merge_input_file:
            merge_input_file.write(merge_files)

        return self._normalize_path(cache_bond_react_merge_normalized / "merge_input.txt")



    def _run_bond_react_merge(self, merge_input_file_path: Path, 
                            molecule_files_all2lmp: list[All2LMPResult]) -> dict[str, Path]:
        """
        Execute LUNAR's bond_react_merge utility to combine and process LAMMPS data files.
        
        This function merges multiple LAMMPS data files into a unified format suitable
        for reactive molecular dynamics simulations, generating both merged data files
        and a force field parameter file.
        
        Args:
            merge_input_file_path (Path): Directory containing the merge input file.
            molecule_files_all2lmp (list[All2LMPResult]): List of All2LMPResult objects containing the LAMMPS data filenames.
        
        Returns:
            dict[str, Path]: Dictionary mapping molecule names and special keys to 
                            their output file paths:
                            - "dataX": Merged data files for data molecules
                            - "preX": LAMMPS molecule files for pre-reaction states
                            - "postX": LAMMPS molecule files for post-reaction states
                            - "force_field_data": Combined force field parameter file
        
        Raises:
            FileNotFoundError: If expected output files are not generated.
        
        Note:
            Uses the following LUNAR bond_react_merge.py command:
            python3 bond_react_merge.py -files infile:merge_input.txt -atomstyle full
        """
        molecule_files_bond_react_merge: dict[str, Path] = {}
        merge_input_file_path = Path(self._normalize_path(merge_input_file_path))
        cache_all2lmp = merge_input_file_path.parent / "all2lmp"
        # Construct and execute the bond_react_merge command
        # Command format: python bond_react_merge.py -files infile:<input_file> -atomstyle full
        subprocess.run(
            [
                sys.executable,                     # Use the current Python interpreter
                self._normalize_path(self.bond_react_merge_py),                # Path to bond_react_merge.py script
                "-files", f"infile:merge_input.txt", # Input file specification
                "-atomstyle", "full",               # LAMMPS atom style
                "-tl", True
            ],
            cwd=merge_input_file_path,              # Run in the directory with input file
            check=True                              # Raise exception if command fails
        )
        self._move_merge_outputs(cache_all2lmp, merge_input_file_path)
        # Map input names to expected output filenames
        for result in molecule_files_all2lmp:
            name = result.id
            if name.startswith("data"):
                n = self._get_ending_integer(name)
                # normalize to "data_<n>"
                tag = f"data_{n}" if n is not None else name
                molecule_files_bond_react_merge[name] = os.path.join(
                    merge_input_file_path, f"{tag}_typed_IFF_merged.data"
                )
            elif name.startswith("pre"):
                # Pre-reaction files generate .lmpmol files
                rxn_number = self._get_ending_integer(name)
                molecule_files_bond_react_merge[name] = (
                    os.path.join(merge_input_file_path, f"pre_{rxn_number}_typed_IFF_merged.lmpmol")
                )
            elif name.startswith("post"):
                # Post-reaction files generate .lmpmol files
                rxn_number = self._get_ending_integer(name)
                molecule_files_bond_react_merge[name] = (
                    os.path.join(merge_input_file_path, f"post_{rxn_number}_typed_IFF_merged.lmpmol")
                )
        
        # Add the force field data file (generated by bond_react_merge)
        molecule_files_bond_react_merge["force_field_data"] = (
            os.path.join(merge_input_file_path, "force_field.data")
        )
        
        # Verify that all expected output files were created
        for name, path in molecule_files_bond_react_merge.items():
            if os.path.isfile(path):
                print(f"[LUNAR bond_react_merge] Generated file for {name} at: {path}")
            else:
                raise FileNotFoundError(
                    f"Expected output file for {name} not found at {path}"
                )
        
        return molecule_files_bond_react_merge


    def lunar_workflow(self,
        updated_inputs_with_3d_mols: SimulationSetup,
        prepared_reactions_with_3d_mols: list[ReactionMetadata],
    ) -> tuple[SimulationSetup, list[ReactionMetadata]]:
        
        # Step 0: Get the force field
        force_field = updated_inputs_with_3d_mols.force_field

        # Step 1: Run atom typing
        atom_typing_result = self._run_LUNAR_atom_typing(updated_inputs_with_3d_mols, prepared_reactions_with_3d_mols, force_field)
        
        # Step 2: Run all2lmp conversion
        all2lmp_result = self._run_LUNAR_all2lmp(atom_typing_result, force_field)
        
        # Step 3: Write bond_react_merge input file
        merge_input_txt_file_path = self._write_bond_react_merge_input(all2lmp_result, self.cache_bond_react_merge, self.cache_all2lmp)
        
        # Step 4: Run bond_react_merge
        lunar_files = self._run_bond_react_merge(merge_input_txt_file_path, all2lmp_result)
        
        return lunar_files
    