"""
LUNAR API Wrapper Module

This module provides a Python interface to the LUNAR (Lammps Utility for 
Reactive Atomistic Simulations) software package. It orchestrates the 
multi-step workflow required to prepare molecular dynamics simulations 
with reactive bond formation/breaking in LAMMPS.

The workflow consists of four main stages:
1. Atom Typing: Assigns force field atom types to molecules
2. Force Field Conversion: Converts to LAMMPS format using all2lmp
3. Merge Input Generation: Creates input files for bond_react_merge
4. Bond Reaction Merge: Combines molecules and reaction templates
"""

import subprocess
import os
import sys
from pathlib import Path
import re
import time
import platform
import shutil
from dataclasses import dataclass
from typing import Optional
from AutoREACTER.input_parser import SimulationSetup
from AutoREACTER.reaction_preparation.lunar_client.locate_lunar import get_LUNAR_loc
from AutoREACTER.reaction_preparation.reaction_processor.prepare_reactions import ReactionMetadata


# =============================================================================
# Data Structures for LUNAR Processing Results
# =============================================================================

@dataclass(slots=True)
class AtomTypingResult:
    """
    Container for atom_typing.py output file paths.
    
    Stores references to the typed data file and NTA (atom type assignment) 
    file generated by LUNAR's atom_typing module.
    """
    id: str                  # Identifier: "data1", "pre1", "post1", etc.
    molecule: bool          # True for data molecules, False for reaction templates
    typed_data_file: Path   # Path to generated *_typed.data file
    nta_file: Path          # Path to generated *.nta file


@dataclass(slots=True)
class All2LMPResult:
    """
    Container for all2lmp.py conversion results.
    
    Stores the path to the LAMMPS-compatible data file generated from
    the atom-typed molecular structure.
    """
    id: str                      # Identifier matching the input
    molecule: bool              # True for molecules, False for templates
    all2lmp_data_file: Path     # Path to generated *_IFF.data file


@dataclass(slots=True)
class DataFiles:
    """Simple container for paired LAMMPS data and molecule files."""
    data_file: Path             # Main *.data file for LAMMPS
    lmp_molecule_file: Path     # Associated *.lmpmol molecule template


@dataclass(slots=True)
class MoleculeFile:
    """Wrapper associating a molecule ID with its generated data files."""
    id: str
    molecule_files: Optional[DataFiles]


@dataclass(slots=True)
class TemplateFile:
    """
    Container for pre- and post-reaction template file pairs.
    
    Used to store the molecular configurations before and after a 
    chemical reaction occurs.
    """
    reaction_id: Optional[int]
    pre_reaction_file: Optional[DataFiles]
    post_reaction_file: Optional[DataFiles]


@dataclass(slots=True)
class LunarFiles:
    """
    Complete collection of output files from the LUNAR workflow.
    
    This represents the final state of the preparation pipeline,
    containing all files necessary for a reactive MD simulation.
    """
    force_field_data: Path             # force_field.data (FF parameters)
    in_file: Path                      # in.fix_bond_react.script (LAMMPS input)

    molecule_files: list[MoleculeFile]
    template_files: list[TemplateFile]


# =============================================================================
# Main API Wrapper Class
# =============================================================================

class LunarAPIWrapper:
    """
    High-level interface for executing LUNAR preparation workflows.
    
    This class manages the execution of LUNAR scripts (atom_typing.py, 
    all2lmp.py, bond_react_merge.py) and handles platform-specific 
    path conversions (notably for WSL environments).
    
    Attributes:
        cache_dir: Root directory for all intermediate and output files
        LUNAR_LOCATION: Path to the LUNAR installation directory
    """

    def __init__(self, cache_dir: Path):
        """
        Initialize the LUNAR wrapper and set up cache directories.
        
        Args:
            cache_dir: Base directory for storing intermediate files.
                      Will create subdirectories for each processing stage.
        """
        self.cache_dir = Path(cache_dir / "lunar")

        # Locate LUNAR installation and key script paths
        self.LUNAR_LOCATION = get_LUNAR_loc(use_gui=False)
        self.atom_typing_py = os.path.join(self.LUNAR_LOCATION, "atom_typing.py")
        self.all2lmp_py = os.path.join(self.LUNAR_LOCATION, "all2lmp.py")
        self.bond_react_merge_py = os.path.join(self.LUNAR_LOCATION, "bond_react_merge.py")

        self._loading_screen("LUNAR API Wrapper Initialization")

        # Create cache structure for different processing stages
        os.makedirs(self.cache_dir, exist_ok=True)

        # Allow override via environment variable
        LUNAR_CACHE_DIR = os.environ.get("LUNAR_CACHE_DIR", self.cache_dir)

        self.cache_atom_typing = os.path.join(LUNAR_CACHE_DIR, "atom_typing")
        self.cache_all2lmp = os.path.join(LUNAR_CACHE_DIR, "all2lmp")
        self.cache_bond_react_merge = os.path.join(LUNAR_CACHE_DIR, "bond_react_merge")

        # Prepare merge prep folder (clean slate)
        self.cache_mergeprep = Path(self.cache_dir) / "all2lmp_2_bondreact_mergeprep"
        if self.cache_mergeprep.exists():
            shutil.rmtree(self.cache_mergeprep)
        self.cache_mergeprep.mkdir(parents=True, exist_ok=True)

        # Ensure all cache directories exist
        for p in (
            self.cache_dir,
            self.cache_atom_typing,
            self.cache_all2lmp,
            self.cache_bond_react_merge,
        ):
            os.makedirs(p, exist_ok=True)

    def _is_wsl(self) -> bool:
        """Check if running inside Windows Subsystem for Linux."""
        return ("microsoft" in platform.release().lower()) or ("WSL_INTEROP" in os.environ)

    def _normalize_path(self, p: str | Path) -> str:
        """
        Convert paths between Windows and WSL formats as needed.
        
        Handles the conversion of Windows paths (C:/path) to WSL paths 
        (/mnt/c/path) and vice versa, ensuring compatibility with LUNAR 
        scripts regardless of the execution environment.
        
        Args:
            p: Input path string or Path object
            
        Returns:
            Normalized path string appropriate for the current platform
        """
        p = str(p).strip().strip('"').strip("'")
        p = p.replace("\\", "/")

        # Convert Windows paths to WSL format
        if self._is_wsl():
            m = re.match(r"^([A-Za-z]):/(.*)$", p)
            if m:
                drive = m.group(1).lower()
                rest = m.group(2)
                return f"/mnt/{drive}/{rest}"
            return os.path.normpath(p)

        host = platform.system().lower()

        # Convert WSL paths to Windows format
        if host == "windows":
            m = re.match(r"^/?mnt/([A-Za-z])/(.*)$", p)
            if m:
                drive = m.group(1).upper()
                rest = m.group(2).replace("/", "\\")
                return f"{drive}:\\{rest}"
            return os.path.normpath(p.replace("/", "\\"))

        return os.path.normpath(p)

    def _get_ending_integer(self, s: str) -> int | None:
        """Extract trailing digits from a string (e.g., 'pre12' -> 12)."""
        match = re.search(r'\d+$', s)
        return int(match.group()) if match else None

    def _move_merge_outputs(self, src_dir: Path, dst_dir: Path):
        """
        Move generated files from all2lmp output to bond_react_merge directory.
        
        Transfers merged data files, molecule files, force field definitions,
        and log files between processing stages.
        """
        src_dir = Path(src_dir)
        dst_dir = Path(dst_dir)
        if not dst_dir.is_dir():
            dst_dir.mkdir(parents=True, exist_ok=True)

        # Move all relevant output files
        for pattern in ("*_merged.data", "*_merged.lmpmol", "force_field.data", "log.lammps", "*.log"):
            for f in src_dir.glob(pattern):
                shutil.move(str(f), str(dst_dir / f.name))

    def _loading_screen(self, name: str = "LUNAR") -> None:
        """
        Display an ASCII art banner with a loading spinner animation.
        
        Provides visual feedback during initialization of long-running 
        LUNAR operations.
        
        Args:
            name: The operation name to display in the loading message.
        """
        # ASCII art banner for LUNAR
        banner = r"""
        █████       █████  █████ ██████   █████   █████████   ███████████  
        ░░███       ░░███  ░░███ ░░██████ ░░███   ███░░░░░███ ░░███░░░░░███ 
        ░███        ░███   ░███  ░███░███ ░███  ░███    ░███  ░███    ░███ 
        ░███        ░███   ░███  ░███░░███░███  ░███████████  ░██████████  
        ░███        ░███   ░███  ░███ ░░██████  ░███░░░░░███  ░███░░░░░███ 
        ░███      █ ░███   ░███  ░███  ░░█████  ░███    ░███  ░███    ░███ 
        ███████████ ░░████████   █████  ░░█████ █████   █████ █████   █████
        ░░░░░░░░░░░   ░░░░░░░░   ░░░░░    ░░░░░ ░░░░░   ░░░░░ ░░░░░   ░░░░░ 
        """
        
        print(banner)
        print(f"Loading {name} ", end="", flush=True)

        # Simple spinner animation
        animation = ["-", "\\", "|", "/"]
        for i in range(10):
            time.sleep(0.1)
            sys.stdout.write("\b" + animation[i % len(animation)])
            sys.stdout.flush()
        
        print("\nReady!")

    def _run_LUNAR_atom_typing(
        self, 
        updated_inputs: SimulationSetup,
        prepared_reactions: list[ReactionMetadata],
        force_field: str
    ) -> tuple[SimulationSetup, list[ReactionMetadata]]:
        """
        Execute atom typing for all molecules and reaction templates.
        
        Runs LUNAR's atom_typing.py to assign force field atom types to:
        1. Monomer/data molecules
        2. Pre-reaction templates (reactants)
        3. Post-reaction templates (products)
        
        Args:
            updated_inputs: Simulation setup containing monomer definitions
            prepared_reactions: List of reactions with 3D molecular structures
            force_field: Target force field name (e.g., "PCFF-IFF")
            
        Returns:
            List of AtomTypingResult objects containing paths to typed files
        """
        atom_typing_result = []

        def run_atom_typing_command(mol_file: Path, output_dir: Path):
            """Helper to execute atom_typing.py with standard parameters."""
            subprocess.run([
                sys.executable,          # Current Python interpreter
                self.atom_typing_py,     # Path to atom_typing.py
                '-topo', str(mol_file),  # Input molecular topology
                '-dir', str(output_dir), # Output directory
                '-ff', force_field,      # Force field specification
                '-del-method', 'mass',   # Delete byproducts by mass
                '-del-crit', '0'        # Deletion threshold (keep all)
            ], check=True)

        # Process monomer/data molecules
        monomer_entries = updated_inputs.monomers
        for entry in monomer_entries:
            if getattr(entry, "status", True) is False:
                continue

            if not entry.molecule_3Dmol_path:
                raise ValueError(
                    f"Active monomer '{entry.name}' is missing molecule_3Dmol_path. "
                    "Ensure 3D geometry preparation completed successfully before atom typing."
                )

            run_atom_typing_command(entry.molecule_3Dmol_path, self.cache_atom_typing)
            # Store references to expected output files
            atom_typing_result.append(
                AtomTypingResult(
                    id=entry.name,
                    molecule=True,
                    typed_data_file=Path(self.cache_atom_typing) / f"{entry.name}_typed.data",
                    nta_file=Path(self.cache_atom_typing) / f"{entry.name}_typed.nta"
                )
            )

            time.sleep(0.1)  # Ensure filesystem sync
                
        # Process reaction templates (pre and post states)
        for reaction in prepared_reactions:
            for mol_path, label in [
                (reaction.reactant_combined_3Dmol_path, "pre"),
                (reaction.product_combined_3Dmol_path, "post"),
            ]:
                # Create separate subdirectories for each reaction state
                output_dir = Path(self.cache_atom_typing) / f"{label}{reaction.reaction_id}"
                output_dir.mkdir(parents=True, exist_ok=True)

                run_atom_typing_command(mol_path, output_dir)

                typed_file = output_dir / f"{mol_path.stem}_typed.data"
                nta_file = output_dir / f"{mol_path.stem}_typed.nta"

                atom_typing_result.append(
                    AtomTypingResult(
                        id=f"{label}{reaction.reaction_id}",
                        typed_data_file=typed_file,
                        nta_file=nta_file,
                        molecule=False
                    )
                )
                time.sleep(0.1)

        # Verify all expected files were created
        for files in atom_typing_result:
            for path in [files.typed_data_file, files.nta_file]:
                if path.is_file():
                    print(f"[LUNAR atom_typing] Generated file for {files.id} at: {path}")
                else:             
                    raise FileNotFoundError(
                        f"Expected output file not found: {path}"
                    )
                            
        return atom_typing_result

    def _frc_file_for_force_field(self, force_field: str) -> str:
        """
        Map force field name to the corresponding .frc parameter file.
        
        LUNAR requires explicit paths to force field definition files.
        This method resolves standard force field names to their file
        locations within the LUNAR installation.
        
        Args:
            force_field: Name of the force field (e.g., "PCFF-IFF", "CVFF")
            
        Returns:
            Absolute path to the .frc file
            
        Raises:
            ValueError: If the force field file is not found or unsupported
        """
        base = Path(self.LUNAR_LOCATION) / "frc_files"

        paths = {
            "PCFF-IFF": base / "pcff_interface_v1_6mBN.frc",
            "PCFF": base / "pcff.frc",
            "Compass": base / "compass_published.frc",
            "CVFF-IFF": base / "cvff_aug.frc",
            "CVFF": base / "cvff.frc",
            "DRIEDING": base / "all2lmp_dreiding.frc",
        }

        if paths[force_field].is_file():
            return str(paths[force_field])
        else:
            raise ValueError(
                f"Force field file not found for {force_field}. "
                f"Please redownload LUNAR from https://github.com/CMMRLab/LUNAR"
            )

    def _run_LUNAR_all2lmp(self, atom_typing_result: list[AtomTypingResult], force_field: str) -> list[All2LMPResult]:
        """
        Convert typed molecules to LAMMPS format.
        
        Executes all2lmp.py to convert the atom-typed data files into
        LAMMPS-compatible data files with proper force field parameters.
        
        Args:
            atom_typing_result: List of results from atom typing stage
            force_field: Target force field name
            
        Returns:
            List of All2LMPResult objects with paths to LAMMPS data files
        """
        # Resolve force field file path (LUNAR sometimes fails to auto-detect)
        frc_file = self._frc_file_for_force_field(force_field)
        
        all2lmp_results = []

        for entry in atom_typing_result:
            name = entry.id
            data_file = entry.typed_data_file
            nta_file = entry.nta_file
            molecule = entry.molecule

            # Execute conversion: typed data -> LAMMPS format
            subprocess.run([
                sys.executable,
                self.all2lmp_py,
                '-topo', str(data_file),
                '-nta', str(nta_file),
                '-frc', frc_file,
                '-dir', self.cache_all2lmp
            ])
            
            # LUNAR naming convention: <name>_typed_IFF.data
            all2lmp_results.append(All2LMPResult(
                id=name,
                all2lmp_data_file=Path(f"{name}_typed_IFF.data"),
                molecule=molecule
            ))

        time.sleep(0.1)  # Filesystem sync
        
        # Verify outputs
        for result in all2lmp_results:
            path = Path(self.cache_all2lmp) / result.all2lmp_data_file
            if Path(path).is_file():
                print(f"[LUNAR all2lmp] Generated file for {result.id} at: {path}")
            else:
                raise FileNotFoundError(
                    f"Expected output file for {result.id} not found at {path}"
                )
        return all2lmp_results

    def _write_bond_react_merge_input(
        self,
        all2lmp_results: list[All2LMPResult],
    ) -> Path:
        """
        Generate the merge_input.txt file for bond_react_merge.py.
        
        This file tells LUNAR which data files are molecules vs. reaction
        templates and how they should be combined. Molecules get 'dataN' 
        tags while reactions get 'preN'/'postN' pairs.
        
        Args:
            all2lmp_results: Results from the all2lmp conversion stage
            
        Returns:
            Path to the generated merge_input.txt file
        """
        cache_dir = Path(self.cache_bond_react_merge)
        cache_dir.mkdir(parents=True, exist_ok=True)

        merge_file = cache_dir / "merge_input.txt"

        # Header with column descriptions
        merge_files = f"""# anything following the "#" character will be ignored

{"# file-tag":<10}{"filename":<150}{"comment (required)"}
"""

        # Tag data molecules as data1, data2, etc.
        data_counter = 1
        for r in all2lmp_results:
            if not r.molecule:
                continue

            full_path = Path(self.cache_all2lmp) / r.all2lmp_data_file
            full_path = self._normalize_path(full_path)

            tag = f"data{data_counter}"
            comment = "# This datafile will have all coeffs in it"

            merge_files += f"{tag:<10}{full_path:<150}{comment}\n"
            data_counter += 1

        # Group reaction templates by ID and tag as preN/postN pairs
        reaction_pairs = {}

        for r in all2lmp_results:
            if r.molecule:
                continue

            rid = self._get_ending_integer(r.id)
            if rid is None:
                continue

            if rid not in reaction_pairs:
                reaction_pairs[rid] = {}

            if r.id.startswith("pre"):
                reaction_pairs[rid]["pre"] = r
            elif r.id.startswith("post"):
                reaction_pairs[rid]["post"] = r

        # Write pre/post pairs in order
        rxn_counter = 1
        for rid in sorted(reaction_pairs):
            pair = reaction_pairs[rid]

            pre = pair.get("pre")
            post = pair.get("post")

            if not pre or not post:
                raise ValueError(f"Incomplete reaction pair for reaction ID {rid}")

            pre_path = self._normalize_path(Path(self.cache_all2lmp) / pre.all2lmp_data_file)
            post_path = self._normalize_path(Path(self.cache_all2lmp) / post.all2lmp_data_file)

            merge_files += f"{f'pre{rxn_counter}':<10}{pre_path:<150}# for rxn{rxn_counter}\n"
            merge_files += f"{f'post{rxn_counter}':<10}{post_path:<150}# for rxn{rxn_counter}\n"

            rxn_counter += 1

        merge_files += f"\n# Specify the parent_directory of where to write results (optional)\n"

        with open(merge_file, "w") as f:
            f.write(merge_files)

        return merge_file

    def _run_bond_react_merge(
        self,
        merge_input_file_path: Path,
        all2lmp_results: list[All2LMPResult]
    ) -> LunarFiles:
        """
        Execute the final bond_react_merge step.
        
        This combines all molecules and reaction templates into the final
        simulation files: merged data files, force_field.data, and the
        LAMMPS input script.
        
        Args:
            merge_input_file_path: Path to merge_input.txt
            all2lmp_results: Results from previous stages (used for verification)
            
        Returns:
            LunarFiles object containing all final output paths
        """
        merge_input_file_path = Path(self._normalize_path(merge_input_file_path))

        molecule_files = []
        template_files = []

        # Execute bond_react_merge with standard reactive simulation parameters
        subprocess.run(
            [
                sys.executable,
                str(self.bond_react_merge_py),
                "-files", "infile:merge_input.txt",
                "-atomstyle", "full",    # Full atom style (molecular + charge)
                "-tl", "T",               # Type labels in data file set to "T" (true) 
                "-wrd", "T",              # Write out Template data files
            ],
            cwd=self.cache_bond_react_merge,  # Run in output directory
            check=True
        )

        output_dir = self.cache_bond_react_merge
        self._move_merge_outputs(self.cache_all2lmp, self.cache_bond_react_merge)

        # Organize output files by type (molecule vs. template)
        for result in all2lmp_results:
            name = result.id
            is_molecule = result.molecule

            if is_molecule:
                molecule_files.append(MoleculeFile(
                    id=name,
                    molecule_files=DataFiles(
                        data_file=Path(output_dir) / f"{name}_typed_IFF_merged.data",
                        lmp_molecule_file=Path(output_dir) / f"{name}_typed_IFF_merged.lmpmol"
                    )
                ))
            else:
                # Handle pre-reaction templates
                if name.startswith("pre"):
                    rid = self._get_ending_integer(name)
                    template_files.append(TemplateFile(
                        reaction_id=rid,
                        pre_reaction_file=DataFiles(
                            data_file=Path(output_dir) / f"{name}_typed_IFF_merged.data",
                            lmp_molecule_file=Path(output_dir) / f"{name}_typed_IFF_merged.lmpmol"
                        ),
                        post_reaction_file=DataFiles(
                            data_file=Path(output_dir) / f"post{rid}_typed_IFF_merged.data",
                            lmp_molecule_file=Path(output_dir) / f"post{rid}_typed_IFF_merged.lmpmol"
                        )
                    ))

        # Verify all expected outputs exist
        for m in molecule_files:
            if m.molecule_files.data_file.is_file() and m.molecule_files.lmp_molecule_file.is_file():
                print(f"[LUNAR bond_react_merge] Generated molecule files for {m.id}")
            else:
                raise FileNotFoundError(
                    f"Missing output files for molecule {m.id}"
                )
                
        for t in template_files:
            pre_exists = t.pre_reaction_file.data_file.is_file()
            post_exists = t.post_reaction_file.data_file.is_file()
            if pre_exists and post_exists:
                print(f"[LUNAR bond_react_merge] Generated template files for reaction {t.reaction_id}")
            else:
                raise FileNotFoundError(
                    Path(t.pre_reaction_file.data_file) or Path(t.post_reaction_file.data_file) / f"Missing template files for reaction {t.reaction_id}"
                )
        
        # Collect all final file paths
        lunar_files = LunarFiles(
            force_field_data=Path(output_dir) / "force_field.data",
            in_file=Path(self.cache_all2lmp) / "in.create_atoms.script",  # LUNAR's generated input script
            molecule_files=molecule_files,
            template_files=template_files
        )

        return lunar_files

    def lunar_workflow(
        self,
        updated_inputs_with_3d_mols: SimulationSetup,
        prepared_reactions_with_3d_mols: list[ReactionMetadata],
    ) -> LunarFiles:
        """
        Execute the complete LUNAR preparation workflow.
        
        Orchestrates the four-stage pipeline:
        1. Atom typing of molecules and reaction templates
        2. Conversion to LAMMPS format (all2lmp)
        3. Generation of merge input configuration
        4. Final bond reaction merge
        
        Args:
            updated_inputs_with_3d_mols: Simulation setup with 3D structures
            prepared_reactions_with_3d_mols: Reaction definitions with 3D structures
            
        Returns:
            LunarFiles containing all generated simulation files
        """
        force_field = updated_inputs_with_3d_mols.force_field

        # Stage 1: Assign atom types using the specified force field
        atom_typing_result = self._run_LUNAR_atom_typing(
            updated_inputs_with_3d_mols,
            prepared_reactions_with_3d_mols,
            force_field
        )

        # Stage 2: Convert to LAMMPS data format with force field parameters
        all2lmp_result = self._run_LUNAR_all2lmp(
            atom_typing_result,
            force_field
        )

        # Stage 3: Create input file for the merge utility
        merge_input_txt_file_path = self._write_bond_react_merge_input(
            all2lmp_result
        )

        # Stage 4: Merge all components into final simulation files
        lunar_files = self._run_bond_react_merge(
            merge_input_txt_file_path,
            all2lmp_result
        )

        return lunar_files
