"""
Foyer API Wrapper Module

This module provides a Python interface to the LUNAR (Lammps Utility for 
Reactive Atomistic Simulations) software package. It orchestrates the 
multi-step workflow required to prepare molecular dynamics simulations 
with reactive bond formation/breaking in LAMMPS.

The workflow consists of four main stages:
1. Atom Typing: Assigns force field atom types to molecules
2. Force Field Conversion: Converts to LAMMPS format using all2lmp
3. Merge Input Generation: Creates input files for bond_react_merge
4. Bond Reaction Merge: Combines molecules and reaction templates
"""

import shutil
import re
import time
from pathlib import Path
import numpy as np
import parmed as pmd
from foyer import Forcefield
from mbuild.formats.lammpsdata import write_lammpsdata
from dataclasses import dataclass
from typing import TYPE_CHECKING, List

# Ensure these match your actual import paths
from AutoREACTER.input_parser import SimulationSetup
from AutoREACTER.reaction_preparation.reaction_processor.prepare_reactions import ReactionMetadata
from AutoREACTER.reaction_preparation.ff_wrapper.lunar_client.locate_lunar import get_LUNAR_loc
from AutoREACTER.reaction_preparation.ff_wrapper.lunar_client.merge_builder import write_bond_react_merge_input
from AutoREACTER.reaction_preparation.ff_wrapper.lunar_client.lunar_executor import LunarExecutor


if TYPE_CHECKING:
    from AutoREACTER.session import Session


@dataclass(slots=True)
class FoyerAtomTypingResult:
    """
    Container for atom_typing.py output file paths.
    
    Stores references to the typed data file and NTA (atom type assignment) 
    file generated by LUNAR's atom_typing module.
    """
    id: str                  # Identifier: "data1", "pre1", "post1", etc.
    molecule: bool           # True for data molecules, False for reaction templates
    typed_data_file: Path    # Path to generated *_typed.data file

@dataclass(slots=True)
class All2LMPResult:
    """Container for all2lmp.py conversion results."""
    id: str                  # Identifier matching the input
    molecule: bool           # True for molecules, False for templates
    all2lmp_data_file: Path  # Path to generated *_IFF.data file


class FoyerAPIWrapper:
    """
    High-level interface for executing Foyer preparation workflows.
    """

    def __init__(self, ARX: "Session", prepared_reactions_with_3d_mols: List[ReactionMetadata]):
        """
        Initialize the Foyer wrapper and set up cache directories.
        """
        self.session = ARX
        self.inputs = ARX.inputs

        # In AutoREACTER, staging_dir is the working/cache directory.
        self.cache_dir = Path(ARX.staging_dir) / "foyer"
        
        # Define specific sub-directories
        self.cache_atom_typing = self.cache_dir / "atom_typing"
        self.cache_all2lmp = self.cache_dir / "all2lmp"
        self.cache_bond_react_merge = self.cache_dir / "merged_files"

        # Ensure all cache directories exist
        for p in (self.cache_dir, self.cache_atom_typing, self.cache_all2lmp, self.cache_bond_react_merge):
            p.mkdir(parents=True, exist_ok=True)

        # Run Foyer atom typing and store results
        self.atom_typing_results = self._run_foyer_atom_typing(
            updated_inputs=self.inputs,
            prepared_reactions=prepared_reactions_with_3d_mols,
            force_field=self.inputs.force_field
        )
        self.LUNAR_LOCATION = Path(get_LUNAR_loc(use_gui=False))
        
        # Convert Foyer-typed files to LAMMPS format using LUNAR's all2lmp.py
        self.all2lmp_results = self._convert_to_all_2_lmp(self.atom_typing_results)
        self.executor = LunarExecutor(lunar_location=self.LUNAR_LOCATION, cache_dir=self.cache_dir)

        merge_input_file = write_bond_react_merge_input(
            cache_bond_react_merge=self.executor.cache_bond_react_merge,
            cache_all2lmp=self.executor.cache_all2lmp,
            all2lmp_results=self.all2lmp_results
        )

        final_foyer_files = self.executor.run_bond_react_merge(
            merge_input_file_path=merge_input_file,
            all2lmp_results=self.all2lmp_results
        )

        self.final_foyer_files = final_foyer_files

    @staticmethod
    def _add_molecule_box(structure, padding=10.0, min_length=20.0):
        """
        Build a loose LAMMPS box around a single molecule.
        Coordinates are in Angstrom.
        mBuild 0.10.x writer scales mins/maxs by 10 for real units,
        so we pass box bounds in nm-like units while atom coordinates remain Angstrom.
        """
        coords_A = np.array(
            [[atom.xx, atom.xy, atom.xz] for atom in structure.atoms],
            dtype=float,
        )

        coord_min_A = coords_A.min(axis=0)
        coord_max_A = coords_A.max(axis=0)

        box_min_A = coord_min_A - padding
        box_max_A = coord_max_A + padding

        lengths_A = box_max_A - box_min_A
        lengths_A = np.maximum(lengths_A, min_length)

        center_A = 0.5 * (coord_min_A + coord_max_A)
        box_min_A = center_A - 0.5 * lengths_A
        box_max_A = center_A + 0.5 * lengths_A

        # mBuild writer expects box-ish values in nm, then writes Angstrom.
        mins_for_writer = (box_min_A / 10.0).tolist()
        maxs_for_writer = (box_max_A / 10.0).tolist()

        structure.box = [
            float(lengths_A[0] / 10.0),
            float(lengths_A[1] / 10.0),
            float(lengths_A[2] / 10.0),
            90.0, 90.0, 90.0,
        ]

        return mins_for_writer, maxs_for_writer

    def _foyer_atom_typing(self, mol_file: Path, output_dir: Path, entry_name: str, molecule: bool, force_field: str):
        force_field = force_field.upper()

        if force_field not in {"OPLSAA", "GAFF"}:
            raise ValueError(
                f"Unsupported force field '{force_field}'. "
                "Supported options are 'OPLSAA' and 'GAFF'."
            )

        if force_field == "GAFF":
            raise NotImplementedError(
                "GAFF is AMBER-family. Use OPLSAA for this direct Foyer -> LAMMPS path for now."
            )

        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)
        mol_file = Path(mol_file)

        # Load molecule as ParmEd Structure
        untyped_molecule = pmd.load_file(str(mol_file), structure=True)

        # Load Foyer force field
        ff = Forcefield(name=force_field.lower())

        # Apply atom typing / parameters
        typed_molecule = ff.apply(
            untyped_molecule, 
            assert_bond_params=False, 
            assert_angle_params=False, 
            assert_dihedral_params=False
        )

        # FIX: Shift molecule IDs so they start at 1 instead of 0
        # LAMMPS prefers molecule IDs to be >= 1 for many compute commands.
        for atom in typed_molecule.atoms:
            if atom.residue.number == 0:
                atom.residue.number = 1

        # Add required simulation box
        mins, maxs = self._add_molecule_box(
            typed_molecule,
            padding=10.0,
            min_length=20.0,
        )

        output_file_path = output_dir / f"{entry_name}_typed.data"

        write_lammpsdata(
            typed_molecule,
            str(output_file_path),
            atom_style="full",
            # unit_style="real",
            # mins=mins,
            # maxs=maxs,
            use_rb_torsions=True,
            use_dihedrals=False,
        )

        print(f"Wrote LAMMPS data file: {output_file_path}")
        return typed_molecule, output_file_path

    def _run_foyer_atom_typing(self, updated_inputs: SimulationSetup, prepared_reactions: list[ReactionMetadata], force_field: str) -> list[FoyerAtomTypingResult]:
        atom_typing_results = []
        self.force_field = force_field

        # Process each molecule in the updated_inputs
        monomer_entries = updated_inputs.monomers
        for entry in monomer_entries:
            print(f"Processing molecule: {entry.name}") 
            if getattr(entry, "status", True) is False:
                continue

            if not entry.molecule_3Dmol_path:
                raise ValueError(
                    f"Active monomer '{entry.name}' is missing molecule_3Dmol_path. "
                    "Ensure 3D geometry preparation completed successfully before atom typing."
                )

            _, output_path = self._foyer_atom_typing(
                mol_file=entry.molecule_3Dmol_path,
                output_dir=self.cache_atom_typing,
                entry_name=entry.name,
                molecule=True,
                force_field=force_field
            )
            
            # Wrap result in the expected dataclass
            atom_typing_results.append(FoyerAtomTypingResult(
                id=entry.name,
                molecule=True,
                typed_data_file=output_path
            ))
            time.sleep(0.1)
        
        # Process each reaction template in the prepared_reactions
        for reaction in prepared_reactions:
            for mol_path, label in [
                (reaction.reactant_combined_3Dmol_path, "pre"),
                (reaction.product_combined_3Dmol_path, "post")
            ]:
                if not mol_path:
                    raise ValueError(
                        f"Reaction template '{reaction.reaction_id}' is missing {label}_combined_3Dmol_path. "
                        "Ensure reaction template preparation completed successfully before atom typing."
                    )
                    
                output_dir = self.cache_atom_typing / f"{label}{reaction.reaction_id}"
                
                _, output_path = self._foyer_atom_typing(
                    mol_file=mol_path,
                    output_dir=output_dir,
                    entry_name=f"{label}{reaction.reaction_id}",
                    molecule=False,
                    force_field=force_field
                )
                
                atom_typing_results.append(FoyerAtomTypingResult(
                    id=f"{label}{reaction.reaction_id}",
                    molecule=False,
                    typed_data_file=output_path
                ))
                time.sleep(0.1)

        return atom_typing_results

    def _convert_to_all_2_lmp(self, atom_typing_results: list[FoyerAtomTypingResult], tag: str = "_IFF") -> list[All2LMPResult]:
        """
        Convert Foyer-typed data files to LAMMPS format using LUNAR's bond_react_merge.py script.
        """
        all2lmp_results = []
        for entry in atom_typing_results:
            all_2_lmp_file = self._rename_and_move_files(
                src=entry.typed_data_file,
                dest=self.cache_all2lmp,
                additional_suffix=tag
            )
            all2lmp_results.append(All2LMPResult(
                id=entry.id,
                molecule=entry.molecule,
                all2lmp_data_file=all_2_lmp_file
            ))

        return all2lmp_results
    @staticmethod
    def _move_merge_outputs(src: Path, dest: Path):
        """Helper to migrate files from all2lmp to bond_react_merge directory if needed."""
        # Add your file moving logic here based on standard OS/Shutil commands if required
        pass

    @staticmethod
    def _rename_and_move_files(src: Path, dest: Path, additional_suffix: str):
        """
        Helper to rename files by adding a suffix and move them to a destination.
        Returns the full Path of the moved file(s).
        """

        src = Path(src)
        dest = Path(dest)
        
        # Ensure destination directory exists
        dest.mkdir(parents=True, exist_ok=True)

        if src.is_file():
            # Handle single file
            new_name = f"{src.stem}{additional_suffix}{src.suffix}"
            dest_file = dest / new_name
            shutil.move(str(src), str(dest_file))
            print(f"Moved and renamed: {src.name} -> {new_name}")
            return dest_file
            
        elif src.is_dir():
            # Handle directory
            moved_files = []
            for file_path in src.iterdir():
                if file_path.is_file():
                    new_name = f"{file_path.stem}{additional_suffix}{file_path.suffix}"
                    dest_file = dest / new_name
                    shutil.move(str(file_path), str(dest_file))
                    print(f"Moved and renamed: {file_path.name} -> {new_name}")
                    moved_files.append(dest_file)
            return moved_files
            
        else:
            raise FileNotFoundError(f"Source path '{src}' does not exist.")

    @staticmethod
    def _get_ending_integer(text: str) -> int:
        """Extracts the trailing integer from strings like 'pre1' or 'post12'."""
        match = re.search(r'\d+$', text)
        return int(match.group()) if match else 0