"""
Foyer API Wrapper Module

This module provides a Python interface to the LUNAR (Lammps Utility for 
Reactive Atomistic Simulations) software package. It orchestrates the 
multi-step workflow required to prepare molecular dynamics simulations 
with reactive bond formation/breaking in LAMMPS.

The workflow consists of four main stages:
1. Atom Typing: Assigns force field atom types to molecules
2. Force Field Conversion: Converts to LAMMPS format using all2lmp
3. Merge Input Generation: Creates input files for bond_react_merge
4. Bond Reaction Merge: Combines molecules and reaction templates
"""

import subprocess
import os
import sys
from pathlib import Path
import re
import time
import platform
import shutil
import importlib.resources as pkg_resources
from typing import Optional
from dataclasses import dataclass
import parmed as pmd
from foyer import Forcefield
from AutoREACTER.input_parser import SimulationSetup
from AutoREACTER.reaction_preparation.lunar_client.locate_lunar import get_LUNAR_loc
from AutoREACTER.reaction_preparation.reaction_processor.prepare_reactions import ReactionMetadata
from AutoREACTER.reaction_preparation.lunar_client.ff_validator import FFValidator
from AutoREACTER.reaction_preparation.lunar_client.foyer_lammps_support import GetForceFieldDataFile, DATAFile2LAMMPSMolecule
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from AutoREACTER.session import ARXSession


# =============================================================================
# Data Structures for LUNAR Processing Results
# =============================================================================

@dataclass(slots=True)
class AtomTypingResult:
    """
    Container for atom_typing.py output file paths.
    
    Stores references to the typed data file and NTA (atom type assignment) 
    file generated by LUNAR's atom_typing module.
    """
    id: str                  # Identifier: "data1", "pre1", "post1", etc.
    molecule: bool          # True for data molecules, False for reaction templates
    typed_data_file: Path   # Path to generated *_typed.data file
    nta_file: Path          # Path to generated *.nta file


@dataclass(slots=True)
class All2LMPResult:
    """
    Container for all2lmp.py conversion results.
    
    Stores the path to the LAMMPS-compatible data file generated from
    the atom-typed molecular structure.
    """
    id: str                      # Identifier matching the input
    molecule: bool              # True for molecules, False for templates
    all2lmp_data_file: Path     # Path to generated *_IFF.data file


@dataclass(slots=True)
class DataFiles:
    """Simple container for paired LAMMPS data and molecule files."""
    data_file: Path             # Main *.data file for LAMMPS
    lmp_molecule_file: Path     # Associated *.lmpmol molecule template


@dataclass(slots=True)
class MoleculeFile:
    """Wrapper associating a molecule ID with its generated data files."""
    id: str
    molecule_files: Optional[DataFiles]


@dataclass(slots=True)
class TemplateFile:
    """
    Container for pre- and post-reaction template file pairs.
    
    Used to store the molecular configurations before and after a 
    chemical reaction occurs.
    """
    reaction_id: Optional[int]
    pre_reaction_file: Optional[DataFiles]
    post_reaction_file: Optional[DataFiles]


@dataclass(slots=True)
class LunarFiles:
    """
    Complete collection of output files from the LUNAR workflow.
    
    This represents the final state of the preparation pipeline,
    containing all files necessary for a reactive MD simulation.
    """
    force_field_data: Path             # force_field.data (FF parameters)
    in_file: Path                      # in.fix_bond_react.script (LAMMPS input)

    molecule_files: list[MoleculeFile]
    template_files: list[TemplateFile]


# =============================================================================
# Main API Wrapper Class
# =============================================================================

class FoyerAPIWrapper:
    """
    High-level interface for executing LUNAR preparation workflows.
    
    This class manages the execution of LUNAR scripts (atom_typing.py, 
    all2lmp.py, bond_react_merge.py) and handles platform-specific 
    path conversions (notably for WSL environments).
    
    Attributes:
        cache_dir: Root directory for all intermediate and output files
        LUNAR_LOCATION: Path to the LUNAR installation directory
    """

    def __init__(self, ARX: "ARXSession"):
        """
        Initialize the LUNAR wrapper and set up cache directories.

        Args:
            ARX: The AutoREACTER session object.
        """

        self.session = ARX
        self.inputs = ARX.inputs

        # In AutoREACTER, staging_dir is the working/cache directory.
        self.cache_dir = Path(ARX.staging_dir) / "lunar"

        # Ensure the cache directory exists
        os.makedirs(self.cache_dir, exist_ok=True)

        Foyer_CACHE_DIR = Path(os.environ.get("LUNAR_CACHE_DIR", self.cache_dir))

        self.cache_atom_typing = Foyer_CACHE_DIR / "atom_typing"
        self.cache_bond_react_merge = Foyer_CACHE_DIR / "bond_react_merge"


        for p in (
            self.cache_dir,
            self.cache_bond_react_merge,
        ):
            os.makedirs(p, exist_ok=True)

        # Run Foyer atom typing and store results
        self.atom_typing_results = self._run_foyer_atom_typing(
            updated_inputs=self.inputs,
            prepared_reactions=self.session.prepared_reactions,
            force_field = self.inputs.force_field
        )
        # Generate the combined force_field.data file for LAMMPS
        self.force_field_data_file = GetForceFieldDataFile(self.atom_typing_results).force_field_data_file

        # Validate the generated force field data file
        FFValidator.validate_force_field_data_file(self.force_field_data_file)


        self.lunar_files = self._run_bond_react_merge(self.atom_typing_results)
       



        

    def _foyer_atom_typing(self, mol_file: Path, output_dir: Path, entry_name: str, molecule: bool, force_field: str) -> AtomTypingResult:

        if force_field not in ['oplsaa', 'gaff']:
            raise ValueError(f"Unsupported force field '{force_field}'. Supported options are 'oplsaa' and 'gaff'.")
        # (ParmEd can read .mol2 directly, or you can convert an RDKit .mol in memory)
        untyped_molecule = pmd.load_file(mol_file, structure=True)

        # 2. Initialize the Foyer force field (Foyer ships with OPLS-AA and GAFF XMLs)
        opls = Forcefield(name=force_field) 

        # # Initialize Foyer with a custom or modified XML force field file
        # custom_ff = Forcefield(forcefield_files='path/to/your_modified_forcefield.xml')

        # # Apply it exactly as before
        # typed_molecule = custom_ff.apply(untyped_molecule)

        # custom_ff = Forcefield(forcefield_files=['base_forcefield.xml', 'custom_modifications.xml'])

        # 3. Apply the force field (Foyer uses SMARTS to assign atom types and parameters)
        typed_molecule = opls.apply(untyped_molecule)

        # 4. Save directly to LAMMPS format!
        typed_molecule.save(output_dir / f"{entry_name}_typed.data")

        return AtomTypingResult(
            id=entry_name,
            molecule=molecule,
            typed_data_file=output_dir / f"{entry_name}_typed.data",
            nta_file = None  # Placeholder for NTA file path
        )
        

    def _run_foyer_atom_typing(
        self, 
        updated_inputs: SimulationSetup,
        prepared_reactions: list[ReactionMetadata],
        force_field: str
    ) -> list[AtomTypingResult]:
        
        atom_typing_result = []
        self.force_field = force_field

        # Process each molecule in the updated_inputs
        monomer_entries = updated_inputs.monomers
        for entry in monomer_entries.values():
            if getattr(entry, "status", True) is False:
                continue

            if not entry.molecule_3Dmol_path:
                raise ValueError(
                    f"Active monomer '{entry.name}' is missing molecule_3Dmol_path. "
                    "Ensure 3D geometry preparation completed successfully before atom typing."
                )

            result = self._foyer_atom_typing(
                mol_file=entry.molecule_3Dmol_path,
                output_dir=self.cache_atom_typing,
                entry_name=entry.name,
                molecule=True,
                force_field=force_field
            )
            atom_typing_result.append(result)
            time.sleep(0.1)  # Simulate processing time for demonstration purposes
        
        # Process each reaction template in the prepared_reactions
        for reaction in prepared_reactions:
            for mol_path, label in [
                (reaction.reactant_combined_3Dmol_path, "pre"),
                (reaction.product_combined_3Dmol_path, "post")
            ]:
                if not mol_path:
                    raise ValueError(
                        f"Reaction template '{reaction.reaction_id}' is missing {label}_combined_3Dmol_path. "
                        "Ensure reaction template preparation completed successfully before atom typing."
                    )
                output_dir = Path(self.cache_atom_typing) / f"{label}{reaction.reaction_id}"
                output_dir.mkdir(parents=True, exist_ok=True)

                result = self._foyer_atom_typing(
                    mol_file=mol_path,
                    output_dir=output_dir,
                    entry_name=f"{label}{reaction.reaction_id}",
                    molecule=False,
                    force_field=force_field
                )
                atom_typing_result.append(result)
                time.sleep(0.1)  # Simulate processing time for demonstration purposes

        return atom_typing_result
    

    def _run_bond_react_merge(
        self,
        atom_typing_results: list[AtomTypingResult]
    ) -> LunarFiles:
        """
        Execute the final bond_react_merge step.
        
        This combines all molecules and reaction templates into the final
        simulation files: merged data files, force_field.data, and the
        LAMMPS input script.
        
        Args:
            atom_typing_results: Results from atom typing stage (used for verification)

        Returns:
            LunarFiles object containing all final output paths
        """

        molecule_files = []
        template_files = []
        output_dir = self.cache_bond_react_merge

        self._move_merge_outputs(self.cache_all2lmp, self.cache_bond_react_merge)

        # Organize output files by type (molecule vs. template)
        for result in atom_typing_results:
            name = result.id
            is_molecule = result.molecule
            typed_data_file = result.typed_data_file


            if is_molecule:
                converter = DATAFile2LAMMPSMolecule(data_file=result.typed_data_file)
                molecule_file_path = converter.extract_and_write(molecule_id=1)
                path_dir = molecule_file_path.parent
                molecule_files.append(MoleculeFile(
                    id=name,
                    molecule_files=DataFiles(
                        data_file=Path(typed_data_file),
                        lmp_molecule_file=Path(molecule_file_path)
                    )
                ))
            else:
                # Handle pre-reaction templates
                converter_pre = DATAFile2LAMMPSMolecule(data_file=result.typed_data_file)
                pre_molecule_file_path = converter_pre.extract_and_write(molecule_id=1)

                if name.startswith("pre"):
                    rid = self._get_ending_integer(name)
                    template_files.append(TemplateFile(
                        reaction_id=rid,
                        pre_reaction_file=DataFiles(
                            data_file=Path(typed_data_file),
                            lmp_molecule_file=Path(pre_molecule_file_path)
                        )
                    ))
                # Handle post-reaction templates
                elif name.startswith("post"):
                    rid = self._get_ending_integer(name)
                    # Find the corresponding pre-reaction template to update
                    converter_post = DATAFile2LAMMPSMolecule(data_file=result.typed_data_file)
                    post_molecule_file_path = converter_post.extract_and_write(molecule_id=1)
                    for template in template_files:
                        if template.reaction_id == rid:
                            template.post_reaction_file = DataFiles(
                                data_file=Path(typed_data_file),
                                lmp_molecule_file=Path(post_molecule_file_path)  # Reusing the same path for simplicity
                            )
                    else:
                        raise ValueError(f"Post-reaction template '{name}' has no matching pre-reaction template with ID {rid}.")

        # Verify all expected outputs exist
        for m in molecule_files:
            if m.molecule_files.data_file.is_file() and m.molecule_files.lmp_molecule_file.is_file():
                print(f"[LUNAR bond_react_merge] Generated molecule files for {m.id}")
            else:
                raise FileNotFoundError(
                    f"Missing output files for molecule {m.id}"
                )
                
        for t in template_files:
            pre_exists = t.pre_reaction_file.data_file.is_file()
            post_exists = t.post_reaction_file.data_file.is_file()
            if pre_exists and post_exists:
                print(f"[LUNAR bond_react_merge] Generated template files for reaction {t.reaction_id}")
            else:
                raise FileNotFoundError(
                    f"Missing template files for reaction {t.reaction_id}: "
                    f"{t.pre_reaction_file.data_file}, {t.post_reaction_file.data_file}"
                )
        
        # Collect all final file paths
        lunar_files = LunarFiles(
            force_field_data=Path(output_dir) / "force_field.data",
            in_file=None, # LUNAR's generated input script
            molecule_files=molecule_files,
            template_files=template_files
        )

        FFValidator(lunar_files)  # Validate the generated force field file

        return lunar_files
        


        
    




        