"""Prepare chemical reactions and generate reaction metadata.

This module processes reaction SMARTS, applies atom mappings, identifies
reaction features such as first-shell atoms, initiators, and byproducts, and
generates metadata and visualizations for downstream analysis.
"""

# WARNING:
# For dataframe and mapping variables, use idx and idxs rather than index or
# indices. Other naming can cause mapping-validation errors.

from dataclasses import dataclass
from functools import reduce
from pathlib import Path
from typing import Dict, List, Optional, TYPE_CHECKING

import pandas as pd
from PIL.Image import Image
from rdkit import Chem
from rdkit.Chem import AllChem, Draw, rdmolops

from AutoREACTER.detectors.reaction_detector import (
    FunctionalGroupInfo,
    ReactionInstance,
)
import logging
logger = logging.getLogger(__name__)
from AutoREACTER.reaction_preparation.reaction_processor.reaction_progression import (
    ReactionProgression,
)
from AutoREACTER.reaction_preparation.deduplication_detector import (
    DeduplicationDetector,
)
from AutoREACTER.reaction_preparation.reaction_processor.utils import (
    add_column_safe,
    add_dict_as_new_columns,
    compare_set,
    prepare_paths,
)
from AutoREACTER.reaction_preparation.reaction_processor.walker import (
    reaction_atom_walker,
)

if TYPE_CHECKING:
    from AutoREACTER.session import Session


class MappingError(Exception):
    """Raised when reactant-to-product atom mapping is invalid."""


class SMARTSParsingError(Exception):
    """Raised when a reactant SMILES string cannot be parsed."""


class ZeroActiveReactionsError(Exception):
    """Raised when no active reactions remain in the dataset."""


@dataclass(slots=True)
class ReactionMetadata:
    """Store molecular structures, mappings, and analysis for one reaction.

    This dataclass holds all information required to describe a single
    prepared reaction, including the combined reactant and product RDKit
    molecules, forward and reverse atom mappings, detected reaction-site
    features, file paths, and activity status.

    Attributes:
        reaction_id: Unique integer identifier assigned to this reaction.
        reactant_combined_RDmol: Combined reactant RDKit molecule.
        product_combined_RDmol: Combined product RDKit molecule.
        reactant_to_product_mapping: Mapping from reactant atom index to
            product atom index.
        product_to_reactant_mapping: Mapping from product atom index to
            reactant atom index.
        template_reactant_to_product_mapping: Subset mapping covering the
            reaction template atoms (reactant index -> product index).
        edge_atoms: Atom indices that form the boundary of the reaction
            template in the reactant molecule.
        first_shell: Reactant atom indices identified as the first-shell
            reaction environment (mapped atoms in the product with template
            map numbers below 999).
        initiators: The two reactant atom indices whose product counterparts
            carry template map numbers 1 and 2.
        byproduct_indices: Reactant indices of atoms that end up in the
            smallest product fragment when atoms are deleted during reaction.
        reaction_smarts: SMARTS string describing the reaction transformation.
        reactant_smiles: Combined SMILES representation of the reactants.
        product_smiles: Combined SMILES representation of the products.
        csv_path: Path to the CSV file storing the atom mapping dataframe.
        reaction_dataframe: DataFrame containing atom mappings and reaction
            feature columns (first_shell, initiators, byproduct_idx, etc.).
        delete_atom: Whether atoms are removed from the reactants during the
            reaction (e.g., condensation byproducts).
        delete_atom_idx: Primary reactant index of the atom to delete, if any.
        reactant_combined_3Dmol_path: Path to the 3D reactant structure file,
            if generated.
        product_combined_3Dmol_path: Path to the 3D product structure file,
            if generated.
        map_file: Path to the standard map file generated by REACTER.
        map_file_with_delete_ids: Path to the map file including deleted atom
            indices, if applicable.
        pre_reaction_file: Path to the pre-reaction molecule file.
        post_reaction_file: Path to the post-reaction molecule file.
        is_radical: Whether the reaction involves radical species.
        radical_atom_idxs: Tuple of reactant indices flagged as radical atoms.
        activity_stats: True if this reaction is active and unique; set to
            False for duplicate or failed reactions so they can be filtered
            downstream.
    """

    reaction_id: int
    reactant_combined_RDmol: Chem.Mol
    product_combined_RDmol: Chem.Mol
    reactant_to_product_mapping: Dict[int, int]
    product_to_reactant_mapping: Dict[int, int]
    template_reactant_to_product_mapping: Optional[Dict[int, int]] = None
    edge_atoms: Optional[List[int]] = None
    first_shell: Optional[List[int]] = None
    initiators: Optional[List[int]] = None
    byproduct_indices: Optional[List[int]] = None
    reaction_smarts: Optional[str] = None
    reactant_smiles: Optional[str] = None
    product_smiles: Optional[str] = None
    csv_path: Optional[Path] = None
    reaction_dataframe: Optional[pd.DataFrame] = None
    delete_atom: bool = True
    delete_atom_idx: Optional[int] = None
    reactant_combined_3Dmol_path: Optional[Path] = None
    product_combined_3Dmol_path: Optional[Path] = None
    map_file: Optional[Path] = None
    map_file_with_delete_ids: Optional[Path] = None
    pre_reaction_file: Optional[Path] = None
    post_reaction_file: Optional[Path] = None
    is_radical: bool = False
    radical_atom_idxs: Optional[tuple[int, ...]] = ()
    activity_stats: bool = True

class PrepareReactions:
    """Build reaction products, atom mappings, metadata, and visualizations.

    This class orchestrates the conversion of detected reaction instances
    (``ReactionInstance`` objects) into fully mapped ``ReactionMetadata``
    objects. It runs RDKit reaction transforms, validates atom mappings,
    identifies first-shell atoms and initiators, detects byproducts, and
    writes per-reaction CSV files to the staging cache.

    Attributes:
        session: Shared AutoREACTER session providing inputs, directories, and
            state such as the reaction ID counter.
        inputs: Shortcut to ``session.inputs``.
        staging_dir: Root staging directory for the run.
        cache: Working cache directory (currently the same as ``staging_dir``).
        csv_cache: Subdirectory where per-reaction mapping CSVs are saved.
    """

    def __init__(self, session: "Session"):
        """Initialize the processor with the shared AutoREACTER session.

        Args:
            session: The active AutoREACTER ``Session`` object. A reaction ID
                counter is attached to the session if it does not already
                exist.
        """
        self.session = session
        self.inputs = session.inputs
        self.staging_dir = Path(session.staging_dir)
        self.cache = self.staging_dir
        self.csv_cache = prepare_paths(self.cache, "csv_cache")

        if not hasattr(session, "reaction_id_counter"):
            session.reaction_id_counter = 0

    def prepare_reactions(self, session):
        """Prepare initial reactions and optionally run reaction progression.

        This is the main entry point. It first builds the initial set of
        mapped reactions, then optionally enters the looping/progression
        phase when ``session.inputs.loop`` is enabled. In both cases it
        verifies that at least one active reaction remains.

        Args:
            session: The active AutoREACTER ``Session`` object.

        Returns:
            The same ``Session`` object, with ``reaction_metadata`` populated.

        Raises:
            ZeroActiveReactionsError: If no active reactions remain after
                preparation (and progression, if enabled).
        """
        prepared_reactions = self._prepare_reactions_stage(session)
        session.reaction_metadata = prepared_reactions

        if session.inputs.loop:
            print("\n[INFO] Reaction progression is enabled. ")
            progression = ReactionProgression(session, preparer=self)
            final_reactions = progression.reaction_progression()
            session.reaction_metadata = final_reactions
            self._zero_active_reactions_error(final_reactions)
        else:
            self._zero_active_reactions_error(prepared_reactions)
            self.deduplication_detector = DeduplicationDetector()
            session.reaction_metadata = (
                self.deduplication_detector.compare_graphs_mol(
                    session.reaction_metadata,     
                    deep_check=self.session.inputs.deep_search,
                )
            )
                    

        return session

    def _zero_active_reactions_error(
        self,
        reaction_metadata: list[ReactionMetadata],
    ) -> None:
        """Raise an error when the metadata contains no active reactions.

        Args:
            reaction_metadata: List of ``ReactionMetadata`` objects to inspect.

        Raises:
            ZeroActiveReactionsError: If none of the reactions have
                ``activity_stats`` set to True.
        """
        if any(reaction.activity_stats for reaction in reaction_metadata):
            return

        raise ZeroActiveReactionsError(
            "No active reactions found in the dataset. "
            "This is an AutoREACTER error indicating that no active "
            "reactions were found in the dataset. Please raise an issue at "
            "https://github.com/NanoCIPHER-Lab/AutoREACTER/issues"
        )

    def _prepare_reactions_stage(
        self,
        session: "Session",
        loop: bool = False,
    ) -> list[ReactionMetadata]:
        """Process reaction instances and add template mapping metadata.

        Converts detected reactions into mapped metadata, removes duplicate
        reactions, and then walks the local environment around each reaction
        to determine template-level mappings and edge atoms. The enriched
        dataframes are saved to CSV for downstream use.

        Args:
            session: The active ``Session`` or, in recursive calls, a list-like
                object containing ``ReactionInstance`` objects. ``loop`` mode
                changes how reactants are sourced from each instance.
            loop: If True, reactants are taken directly from the RDKit
                molecules attached to the reaction instance (used during the
                progression/looping stage).

        Returns:
            A list of unique ``ReactionMetadata`` objects with template
            mappings and edge atoms populated for active reactions.
        """
        try:
            reaction_instances = session.reaction_instances
        except AttributeError:
            reaction_instances = session

        reaction_metadata = self._process_reaction_instances(
            reaction_instances,
            loop=loop,
        )
        unique_reaction_metadata = self._detect_duplicates(
            reaction_metadata
        )

        for reaction in unique_reaction_metadata:
            if not reaction.activity_stats:
                continue

            reactant_mol = reaction.reactant_combined_RDmol
            reaction_dataframe = reaction.reaction_dataframe
            csv_save_path = reaction.csv_path

            # Extract the full atom mapping and first-shell list from the
            # dataframe; these are needed to determine the template subset.
            fully_mapped_dict = reaction_dataframe.set_index(
                "reactant_idx"
            )["product_idx"].to_dict()
            first_shell = reaction_dataframe["first_shell"].dropna().tolist()

            # Walk outward from the first-shell atoms to find the minimal
            # template mapping and the edge atoms of the reaction site.
            template_mapped_dict, edge_atoms = reaction_atom_walker(
                reactant_mol,
                first_shell,
                fully_mapped_dict,
            )

            # Attach template mapping columns and edge-atom list to the
            # dataframe, then persist the updated version to CSV.
            reaction_dataframe = add_dict_as_new_columns(
                reaction_dataframe,
                template_mapped_dict,
                titles=[
                    "template_reactant_idx",
                    "template_product_idx",
                ],
            )
            reaction_dataframe = add_column_safe(
                reaction_dataframe,
                edge_atoms,
                "edge_atoms",
            )

            reaction.reaction_dataframe = reaction_dataframe.copy()
            reaction_dataframe.to_csv(csv_save_path, index=False)
            reaction.edge_atoms = edge_atoms
            reaction.template_reactant_to_product_mapping = (
                template_mapped_dict
            )

        return unique_reaction_metadata

    def _process_reaction_instances(
        self,
        detected_reactions: list[ReactionInstance],
        loop: bool = False,
    ) -> list[ReactionMetadata]:
        """Convert reaction instances into mapped reaction metadata.

        For each detected reaction, this method prepares the reactant RDKit
        molecules (from SMILES in the initial stage or from existing molecules
        in loop mode), builds the RDKit reaction object, and delegates product
        generation and mapping to ``_process_reaction_products``.

        Args:
            detected_reactions: List of ``ReactionInstance`` objects produced
                by the reaction detector.
            loop: Whether the call is part of the reaction progression loop.

        Returns:
            A list of ``ReactionMetadata`` objects, one per successfully
            mapped product set.
        """
        reaction_metadata: list[ReactionMetadata] = []

        for reaction in detected_reactions:
            if loop and (
                reaction.monomer_1.rdkit_mol is None
                or (
                    reaction.monomer_2 is not None
                    and reaction.monomer_2.rdkit_mol is None
                )
            ):
                logger.warning(
                    "Skipping reaction %s: monomer rdkit_mol is None "
                    "(likely failed sanitization upstream).",
                    reaction.reaction_name,
                )
                continue

            same_reactants = reaction.same_reactants
            forced_idxs_1 = None
            forced_idxs_2 = None

            if loop:
                # In loop mode, restrict accepted initiators to atoms that
                # belong to the previously matched functional groups. This
                # prevents the reaction from jumping to an unrelated site
                # during polymerization-like progression.
                forced_idxs_1 = self._flatten_fg_indexes(
                    reaction.functional_group_1
                )
                if reaction.functional_group_2 is not None:
                    forced_idxs_2 = self._flatten_fg_indexes(
                        reaction.functional_group_2
                    )

                mol_reactant_1 = self._copy_loop_reactant_mol(
                    reaction.monomer_1
                )
                monomer_2 = (
                    reaction.monomer_1
                    if same_reactants
                    else reaction.monomer_2
                )
                mol_reactant_2 = self._copy_loop_reactant_mol(
                    monomer_2
                )

                # The ReactionInstance already defines reactant-slot order.
                reaction_tuple = [[mol_reactant_1, mol_reactant_2]]
            else:
                reactant_smiles_1 = reaction.monomer_1.smiles
                reactant_smiles_2 = (
                    reactant_smiles_1
                    if same_reactants
                    else reaction.monomer_2.smiles
                )
                mol_reactant_1, mol_reactant_2 = self._build_reactants(
                    reactant_smiles_1,
                    reactant_smiles_2,
                )
                reaction_tuple = self._build_reaction_tuple(
                    same_reactants,
                    mol_reactant_1,
                    mol_reactant_2,
                )

            rxn = self._build_reaction(reaction.reaction_smarts)
            reaction_metadata = self._process_reaction_products(
                rxn=rxn,
                csv_cache=self.csv_cache,
                reaction_tuple=reaction_tuple,
                delete_atoms=reaction.delete_atom,
                reaction_metadata=reaction_metadata,
                forced_indexes_1=forced_idxs_1,
                forced_indexes_2=forced_idxs_2,
            )

        return reaction_metadata

    def _copy_loop_reactant_mol(self, monomer_role) -> Chem.Mol:
        """Copy a loop-mode reactant without changing generated products.

        Initial input monomers are stored as RDKit molecules without explicit
        hydrogens before the loop starts, so they still need ``Chem.AddHs``.
        Generated products already passed through reaction-progression
        sanitization and may contain explicit hydrogens, radical electrons,
        and no-implicit flags. Adding hydrogens to those products again can
        change the representation that is later sent to LUNAR.
        """
        if monomer_role is None or monomer_role.rdkit_mol is None:
            raise SMARTSParsingError(
                "Loop-mode reactant is missing its RDKit molecule."
            )

        loop_mol = Chem.Mol(monomer_role.rdkit_mol)
        loop_mol.UpdatePropertyCache(strict=False)

        if getattr(monomer_role, "is_monomer", False):
            return Chem.AddHs(loop_mol)

        return loop_mol

    def _process_reaction_products(
        self,
        rxn: Chem.rdChemReactions.ChemicalReaction,
        csv_cache: Path,
        reaction_tuple: list,
        delete_atoms: bool = True,
        reaction_metadata: Optional[list[ReactionMetadata]] = None,
        forced_indexes_1: Optional[set] = None,
        forced_indexes_2: Optional[set] = None,
    ) -> list[ReactionMetadata]:
        """Run reactions and build metadata for each generated product set.

        Applies the RDKit reaction to each reactant pair, attempts reverse
        ordering on failure, builds atom mappings, validates them, identifies
        first-shell atoms and initiators, detects byproducts, and stores the
        result as ``ReactionMetadata`` with a persistent CSV file.

        Args:
            rxn: RDKit ``ChemicalReaction`` object built from SMARTS.
            csv_cache: Directory where mapping CSV files are written.
            reaction_tuple: List of [reactant_1, reactant_2] pairs to react.
            delete_atoms: Whether the reaction removes a byproduct fragment.
            reaction_metadata: Mutable list to append new metadata to. A new
                list is created if None is supplied.
            forced_indexes_1: Allowed initiator atom indices for reactant 1
                (used in loop mode). None disables the filter.
            forced_indexes_2: Allowed initiator atom indices for reactant 2
                (used in loop mode). None disables the filter.

        Returns:
            The updated list of ``ReactionMetadata`` objects.
        """
        if reaction_metadata is None:
            reaction_metadata = []

        for pair in reaction_tuple:
            r1 = Chem.Mol(pair[0])
            r2 = Chem.Mol(pair[1])
            self._assign_atom_map_numbers_and_set_isotopes(r1, r2)

            products = rxn.RunReactants((r1, r2))
            if not products:
                # print(
                #     "Reaction failed in default order, "
                #     "trying reverse order..."
                # ) # this was a debug print, not needed in normal operation
                products = rxn.RunReactants((r2, r1))

            if not products:
                print(
                    "Reaction failed in both orders, "
                    "skipping this reactant pair."
                )
                print(
                    f"\n[ERROR] RDKit failed to react "
                    f"{r1.GetNumAtoms()} atoms with "
                    f"{r2.GetNumAtoms()} atoms."
                )
                print(f"Reactant 1 SMILES: {Chem.MolToSmiles(r1)}")
                print(f"Reactant 2 SMILES: {Chem.MolToSmiles(r2)}")
                print(
                    "Reaction SMARTS: "
                    f"{Chem.rdChemReactions.ReactionToSmarts(rxn)}\n"
                )

            for product_set in products:
                reactant_combined = Chem.CombineMols(r1, r2)
                product_combined = (
                    product_set[0]
                    if len(product_set) == 1
                    else reduce(Chem.CombineMols, product_set)
                )

                self._reassign_atom_map_numbers_by_isotope(
                    product_combined
                )
                mapping_dict, mapping_df = self._build_atom_index_mapping(
                    reactant_combined,
                    product_combined,
                )
                reverse_mapping = {
                    product_idx: reactant_idx
                    for reactant_idx, product_idx in mapping_dict.items()
                }

                self._reveal_template_map_numbers(product_combined)
                self._validate_mapping(
                    mapping_df,
                    reactant_combined,
                    product_combined,
                )

                first_shell, initiator_idxs = (
                    self._assign_first_shell_and_initiators(
                        reactant_combined,
                        product_combined,
                        reverse_mapping,
                    )
                )

                # When loop-mode restrictions are active, discard product sets
                # whose initiators fall outside the allowed functional-group
                # atom sets.
                if (
                    forced_indexes_1 is not None
                    or forced_indexes_2 is not None
                ) and not self._initiators_within_forced_indexes(
                    initiator_idxs,
                    r1.GetNumAtoms(),
                    forced_indexes_1,
                    forced_indexes_2,
                ):
                    continue

                byproduct_reactant_idxs = self._detect_byproducts(
                    product_combined,
                    reverse_mapping,
                    delete_atoms,
                )

                reaction_df = pd.concat(
                    [
                        mapping_df,
                        pd.Series(first_shell, name="first_shell"),
                        pd.Series(initiator_idxs, name="initiators"),
                        pd.Series(
                            byproduct_reactant_idxs,
                            name="byproduct_idx",
                        ),
                    ],
                    axis=1,
                ).astype(pd.Int64Dtype())

                self.session.reaction_id_counter += 1
                reaction_id = self.session.reaction_id_counter
                csv_path = csv_cache / f"reaction_{reaction_id}.csv"

                self._clear_isotopes(
                    reactant_combined,
                    product_combined,
                )
                reaction_df.to_csv(csv_path, index=False)

                reaction_metadata.append(
                    ReactionMetadata(
                        reaction_id=reaction_id,
                        reactant_combined_RDmol=reactant_combined,
                        product_combined_RDmol=product_combined,
                        reactant_to_product_mapping=mapping_dict,
                        product_to_reactant_mapping=reverse_mapping,
                        first_shell=first_shell,
                        initiators=initiator_idxs,
                        byproduct_indices=byproduct_reactant_idxs,
                        csv_path=csv_path,
                        reaction_dataframe=reaction_df,
                        delete_atom=delete_atoms,
                        delete_atom_idx=(
                            byproduct_reactant_idxs[0]
                            if byproduct_reactant_idxs
                            else None
                        ),
                        activity_stats=True,
                    )
                )
        return reaction_metadata

    def _detect_duplicates(
        self,
        reaction_metadata_list: list[ReactionMetadata],
    ) -> list[ReactionMetadata]:
        """Return unique reaction metadata based on reactants and products.

        Two reactions are considered duplicates if their combined reactant and
        combined product molecules are structurally identical. Duplicate
        entries are retained in the returned list but marked inactive via
        ``activity_stats = False``.

        Args:
            reaction_metadata_list: List of ``ReactionMetadata`` objects to
                deduplicate.

        Returns:
            The same list, with duplicate reactions flagged as inactive.
        """
        unique_metadata: list[ReactionMetadata] = []

        for reaction in reaction_metadata_list:
            if compare_set(
                unique_metadata,
                reaction.reactant_combined_RDmol,
                reaction.product_combined_RDmol,
            ):
                unique_metadata.append(reaction)
            else:
                reaction.activity_stats = False

        return unique_metadata

    def _flatten_fg_indexes(
        self,
        fg: Optional["FunctionalGroupInfo"],
    ) -> Optional[set]:
        """Flatten functional-group match indexes into one allowed idx set.

        A functional group can have multiple SMARTS matches, each match being
        a tuple or list of atom indices. This helper merges all matches for
        both functional group slots into a single set of allowed atom indices.

        Args:
            fg: ``FunctionalGroupInfo`` object, or None.

        Returns:
            A set of atom indices, or None if no matches are available.
        """
        if fg is None:
            return None

        combined = set()
        if fg.fg_1_indexes:
            combined.update(
                atom_idx
                for match in fg.fg_1_indexes
                for atom_idx in match
            )
        if fg.fg_2_indexes:
            combined.update(
                atom_idx
                for match in fg.fg_2_indexes
                for atom_idx in match
            )

        return combined or None

    def _initiators_within_forced_indexes(
        self,
        initiator_idxs: list[int],
        r1_atom_count: int,
        forced_indexes_1: Optional[set],
        forced_indexes_2: Optional[set],
    ) -> bool:
        """Check initiator atoms against their reactants' allowed idx sets.

        Initiator indices are global indices into the combined reactant
        molecule. Indices below ``r1_atom_count`` belong to reactant 1; the
        rest belong to reactant 2 after subtracting the offset.

        Args:
            initiator_idxs: Reactant indices of the two initiator atoms.
            r1_atom_count: Number of atoms in reactant 1 before combining.
            forced_indexes_1: Allowed indices for reactant 1, or None.
            forced_indexes_2: Allowed indices for reactant 2, or None.

        Returns:
            True if every initiator lies within its respective allowed set,
            or if no restriction is applied to that reactant.
        """
        for idx in initiator_idxs:
            if idx < r1_atom_count:
                if (
                    forced_indexes_1 is not None
                    and idx not in forced_indexes_1
                ):
                    return False
            else:
                local_idx = idx - r1_atom_count
                if (
                    forced_indexes_2 is not None
                    and local_idx not in forced_indexes_2
                ):
                    return False

        return True

    def _index_based_reaction_preparation(
        self,
        reaction_instances,
    ):
        """Prepare index-based reaction instances in loop mode.

        Creates a fresh ``PrepareReactions`` instance and runs the preparation
        stage with ``loop=True``. This helper is typically invoked by the
        progression machinery when reactions need to be re-prepared after each
        loop iteration.

        Args:
            reaction_instances: Collection of ``ReactionInstance`` objects.

        Returns:
            List of ``ReactionMetadata`` objects produced in loop mode.
        """
        prepare_reactions = PrepareReactions(self.session)
        return prepare_reactions._prepare_reactions_stage(
            reaction_instances,
            loop=True,
        )

    def _assign_first_shell_and_initiators(
        self,
        reactant_combined: Chem.Mol,
        product_combined: Chem.Mol,
        reversed_mapping_dict: dict[int, int],
    ) -> tuple[list[int], list[int]]:
        """Identify first-shell atoms and the two reaction initiators.

        First-shell atoms are defined as product atoms whose atom map number
        is below 999 (i.e., they were assigned a template map number by the
        reaction SMARTS) and that can be traced back to a reactant atom via
        the reverse mapping. The two atoms whose product counterparts have map
        numbers 1 and 2 are labeled as initiators.

        Args:
            reactant_combined: Combined reactant molecule with isotope-based
                tracking map numbers still intact on product-mapped atoms.
            product_combined: Combined product molecule with template map
                numbers revealed via ``_reveal_template_map_numbers``.
            reversed_mapping_dict: Mapping from product atom index to reactant
                atom index.

        Returns:
            A tuple of (first_shell, initiator_idxs), where each is a list of
            reactant atom indices.

        Raises:
            ValueError: If a mapped product atom has no reverse mapping, or if
                the number of initiator atoms is not exactly two.
        """
        first_shell = []
        initiator_idxs = []

        for product_atom in product_combined.GetAtoms():
            map_num = product_atom.GetAtomMapNum()
            if map_num >= 999:
                continue

            product_idx = product_atom.GetIdx()
            if product_idx not in reversed_mapping_dict:
                raise ValueError(
                    f"Mapping error: product atom {product_idx} "
                    "not found in mapping_dict"
                )

            reactant_idx = reversed_mapping_dict[product_idx]
            reactant_atom = reactant_combined.GetAtomWithIdx(
                reactant_idx
            )
            reactant_atom.SetAtomMapNum(map_num)
            first_shell.append(reactant_idx)

            if map_num in (1, 2):
                initiator_idxs.append(reactant_idx)

        if len(initiator_idxs) != 2:
            raise ValueError(
                f"Expected 2 initiators, got {len(initiator_idxs)}: "
                f"{initiator_idxs}"
            )

        return first_shell, initiator_idxs

    def _detect_byproducts(
        self,
        product_combined: Chem.Mol,
        reversed_mapping_dict: dict[int, int],
        delete_atoms: bool,
    ) -> list[int]:
        """Map atoms in the smallest product fragment to reactant idxs.

        When ``delete_atoms`` is True, the reaction is assumed to produce a
        removable byproduct. The smallest disconnected fragment in the product
        is treated as that byproduct, and its atoms are translated back to the
        reactant-index space using the reverse mapping.

        Args:
            product_combined: Combined product molecule, possibly containing
                multiple disconnected fragments.
            reversed_mapping_dict: Mapping from product atom index to reactant
                atom index.
            delete_atoms: If False, an empty list is returned immediately.

        Returns:
            Reactant indices of the atoms composing the detected byproduct.
        """
        if not delete_atoms:
            return []

        fragment_idxs = rdmolops.GetMolFrags(product_combined)
        smallest_fragment_idxs = min(fragment_idxs, key=len)

        return [
            reversed_mapping_dict[product_idx]
            for product_idx in smallest_fragment_idxs
            if product_idx in reversed_mapping_dict
        ]

    def _validate_mapping(
        self,
        df: pd.DataFrame,
        reactant: Chem.Mol,
        product: Chem.Mol,
    ) -> None:
        """Validate mapping columns, uniqueness, bounds, and completeness.

        Ensures that every atom in both the reactant and product molecules is
        accounted for exactly once in the mapping dataframe and that all
        indices are within bounds.

        Args:
            df: DataFrame containing at least ``reactant_idx`` and
                ``product_idx`` columns.
            reactant: Combined reactant RDKit molecule.
            product: Combined product RDKit molecule.

        Raises:
            MappingError: If the dataframe is empty, missing required columns,
                unbalanced, contains duplicates, has out-of-bounds indices, or
                does not cover every atom in either molecule.
        """
        if df is None or df.empty:
            raise MappingError(
                "Mapping validation failed: empty dataframe"
            )

        required_cols = {"reactant_idx", "product_idx"}
        if not required_cols.issubset(df.columns):
            raise MappingError(
                "Mapping validation error: required columns "
                f"{required_cols} not found in dataframe."
            )

        r_idxs = df["reactant_idx"].dropna().tolist()
        p_idxs = df["product_idx"].dropna().tolist()

        if len(r_idxs) != len(p_idxs):
            raise MappingError(
                "Mapping validation error: mismatch in atom counts "
                "between reactant and product."
            )
        if len(set(r_idxs)) != len(r_idxs):
            raise MappingError(
                "Mapping validation error: duplicate idxs found in "
                "reactant mapping."
            )
        if len(set(p_idxs)) != len(p_idxs):
            raise MappingError(
                "Mapping validation error: duplicate idxs found in "
                "product mapping."
            )
        if any(
            idx < 0 or idx >= reactant.GetNumAtoms()
            for idx in r_idxs
        ):
            raise MappingError(
                "Mapping validation error: reactant idx out of bounds."
            )

        if any(
            idx < 0 or idx >= product.GetNumAtoms()
            for idx in p_idxs
        ):
            raise MappingError(
                "Mapping validation error: product idx out of bounds."
            )
        if len(r_idxs) != reactant.GetNumAtoms():
            raise MappingError(
                "Mapping validation error: incomplete mapping for "
                "reactant."
            )
        if len(p_idxs) != product.GetNumAtoms():
            raise MappingError(
                "Mapping validation error: incomplete mapping for product."
            )

    def _assign_atom_map_numbers_and_set_isotopes(
        self,
        r1: Chem.Mol,
        r2: Chem.Mol,
    ) -> None:
        """Assign tracking map numbers and isotopes to reactant atoms.

        Atoms in reactant 1 are tagged with 1001-based numbers, and atoms in
        reactant 2 with 2001-based numbers. Both the atom map number and the
        isotope are set to the same value so that product atoms can later be
        traced back to their originating reactant atoms regardless of how the
        reaction SMARTS rewrites the molecule.

        Args:
            r1: First reactant molecule; modified in place.
            r2: Second reactant molecule; modified in place.
        """
        for atom in r1.GetAtoms():
            idx = 1001 + atom.GetIdx()
            atom.SetAtomMapNum(idx)
            atom.SetIsotope(idx)

        for atom in r2.GetAtoms():
            idx = 2001 + atom.GetIdx()
            atom.SetAtomMapNum(idx)
            atom.SetIsotope(idx)

    def _reassign_atom_map_numbers_by_isotope(
        self,
        mol: Chem.Mol,
    ) -> None:
        """Restore product atom map numbers from tracking isotopes.

        After RDKit runs the reaction, atoms that survive from the reactants
        retain their original isotope values. This method copies those values
        back into the atom map number slot and clears the isotope so that the
        product can be aligned with the reactant via ``_build_atom_index_mapping``.

        Args:
            mol: Product molecule; modified in place.
        """
        for atom in mol.GetAtoms():
            surviving_idx = atom.GetIsotope()
            if surviving_idx != 0:
                atom.SetAtomMapNum(surviving_idx)
                atom.SetIsotope(0)

    def _build_atom_index_mapping(
        self,
        reactant_combined: Chem.Mol,
        product_combined: Chem.Mol,
    ) -> tuple[dict[int, int], pd.DataFrame]:
        """Build reactant-to-product atom mapping using map numbers.

        Matches atoms across the combined reactant and product molecules by
        their shared atom map numbers. Atoms with map number 0 (e.g., newly
        added hydrogens or atoms that lost their tag) are ignored because they
        cannot be traced unambiguously.

        Args:
            reactant_combined: Combined reactant molecule with tracking map
                numbers on surviving atoms.
            product_combined: Combined product molecule with matching map
                numbers on surviving atoms.

        Returns:
            A tuple of (mapping_dict, mapping_df). ``mapping_dict`` maps
            reactant atom index to product atom index. ``mapping_df`` contains
            the same data in two columns, ``reactant_idx`` and ``product_idx``.
        """
        product_map = {
            atom.GetAtomMapNum(): atom.GetIdx()
            for atom in product_combined.GetAtoms()
            if atom.GetAtomMapNum() != 0
        }

        mapping_dict = {}
        rows = []

        for reactant_atom in reactant_combined.GetAtoms():
            reactant_map_num = reactant_atom.GetAtomMapNum()
            if (
                reactant_map_num == 0
                or reactant_map_num not in product_map
            ):
                continue

            reactant_idx = reactant_atom.GetIdx()
            product_idx = product_map[reactant_map_num]
            mapping_dict[reactant_idx] = product_idx
            rows.append(
                {
                    "reactant_idx": reactant_idx,
                    "product_idx": product_idx,
                }
            )

        return mapping_dict, pd.DataFrame(rows)

    def _reveal_template_map_numbers(self, mol: Chem.Mol) -> None:
        """Restore template map numbers from RDKit's ``old_mapno`` property.

        RDKit reaction SMARTS with atom maps stores the original template map
        number in the ``old_mapno`` atom property. Copying it back to the atom
        map number makes the reaction-center atoms visible to downstream first-
        shell and initiator detection.

        Args:
            mol: Product molecule; modified in place.
        """
        for atom in mol.GetAtoms():
            if atom.HasProp("old_mapno"):
                atom.SetAtomMapNum(atom.GetIntProp("old_mapno"))

    def _clear_isotopes(
        self,
        mol_1: Chem.Mol,
        mol_2: Chem.Mol,
    ) -> None:
        """Remove tracking isotopes from two molecules.

        Args:
            mol_1: First molecule; modified in place.
            mol_2: Second molecule; modified in place.
        """
        for atom in mol_1.GetAtoms():
            atom.SetIsotope(0)
        for atom in mol_2.GetAtoms():
            atom.SetIsotope(0)

    def _build_reaction(
        self,
        rxn_smarts: str,
    ) -> Chem.rdChemReactions.ChemicalReaction:
        """Build an RDKit reaction from a SMARTS string.

        Args:
            rxn_smarts: Reaction SMARTS describing the transformation.

        Returns:
            An RDKit ``ChemicalReaction`` object ready for ``RunReactants``.
        """
        return AllChem.ReactionFromSmarts(rxn_smarts)

    def _build_reactants(
        self,
        reactant_smiles_1: str,
        reactant_smiles_2: str,
    ) -> tuple[Chem.Mol, Chem.Mol]:
        """Build two explicit-hydrogen reactant molecules from SMILES.

        Args:
            reactant_smiles_1: SMILES string for the first reactant.
            reactant_smiles_2: SMILES string for the second reactant.

        Returns:
            A tuple of two RDKit molecules with explicit hydrogens added.

        Raises:
            SMARTSParsingError: If either SMILES string cannot be parsed by
                RDKit.
        """
        mol_reactant_1 = Chem.MolFromSmiles(reactant_smiles_1)
        if mol_reactant_1 is None:
            raise SMARTSParsingError(
                "Failed to parse first reactant SMILES: "
                f"{reactant_smiles_1!r}"
            )

        mol_reactant_2 = Chem.MolFromSmiles(reactant_smiles_2)
        if mol_reactant_2 is None:
            raise SMARTSParsingError(
                "Failed to parse second reactant SMILES: "
                f"{reactant_smiles_2!r}"
            )

        return Chem.AddHs(mol_reactant_1), Chem.AddHs(mol_reactant_2)

    def _build_reaction_tuple(
        self,
        same_reactants: bool,
        mol_reactant_1: Chem.Mol,
        mol_reactant_2: Chem.Mol,
    ) -> list:
        """Build the ordered reactant pairs to pass to RDKit.

        When the two reactants are the same molecule, only one ordering is
        needed. Otherwise, both orderings are attempted so that asymmetric
        SMARTS can match either reactant in either slot.

        Args:
            same_reactants: True if reactant 1 and reactant 2 are identical.
            mol_reactant_1: First reactant molecule.
            mol_reactant_2: Second reactant molecule.

        Returns:
            A list of [reactant_1, reactant_2] pairs.
        """
        if same_reactants:
            return [[mol_reactant_1, mol_reactant_1]]

        return [
            [mol_reactant_1, mol_reactant_2],
            [mol_reactant_2, mol_reactant_1],
        ]

    def _is_consecutive(self, num_list: list[int]) -> bool:
        """Return whether values are unique consecutive integers.

        Args:
            num_list: List of integers to inspect.

        Returns:
            True if the list is non-empty, contains no duplicates, and spans a
            contiguous range of integers; otherwise False.
        """
        if not num_list:
            return False

        return (
            len(set(num_list)) == len(num_list)
            and max(num_list) - min(num_list) + 1 == len(num_list)
        )

    def reaction_templates_highlighted_image_grid(
        self,
        session: "Session",
        highlight_type: str = "template",
    ) -> Image:
        """Generate a two-column grid of highlighted reaction structures.

        Renders each active reaction as a reactant/product pair, highlighting
        atoms according to the chosen highlight type. Supported types are:
        ``template`` (template reaction atoms), ``edge`` (edge atoms of the
        reaction template), ``initiators`` (reaction initiators), and
        ``delete`` (byproduct atoms).

        Args:
            session: The active AutoREACTER ``Session`` object containing the
                populated ``reaction_metadata`` list.
            highlight_type: Category of atoms to highlight. One of
                ``"template"``, ``"edge"``, ``"initiators"``, or ``"delete"``.

        Returns:
            A PIL ``Image`` containing the grid, or None if no reaction
            metadata is available. Atom map numbers are cleared before drawing
            to keep the visualization uncluttered.
        """
        metadata_list = session.reaction_metadata
        if not metadata_list:
            return None

        mols = []
        highlight_lists = []
        highlight_colors = []
        names = []

        for metadata in metadata_list:
            if not metadata.activity_stats:
                continue

            reactant = Chem.RWMol(metadata.reactant_combined_RDmol)
            product = Chem.RWMol(metadata.product_combined_RDmol)
            names.extend(
                [
                    f"pre_{metadata.reaction_id}",
                    f"post_{metadata.reaction_id}",
                ]
            )

            # Remove atom map numbers so they do not clutter the image.
            for atom in reactant.GetAtoms():
                atom.SetAtomMapNum(0)
            for atom in product.GetAtoms():
                atom.SetAtomMapNum(0)

            reaction_df = metadata.reaction_dataframe
            atoms: List[int] = []
            color_map: Dict[int, tuple] = {}

            if highlight_type == "template":
                atoms = list(
                    (
                        metadata.template_reactant_to_product_mapping
                        or {}
                    ).keys()
                )
                color_map = {
                    atom_idx: (0.2, 0.6, 1.0)
                    for atom_idx in atoms
                }
            elif highlight_type == "edge":
                atoms = metadata.edge_atoms or []
                color_map = {
                    atom_idx: (1.0, 0.4, 0.0)
                    for atom_idx in atoms
                }
            elif highlight_type == "initiators":
                if reaction_df is not None:
                    atoms = (
                        reaction_df["initiators"]
                        .dropna()
                        .astype(int)
                        .tolist()
                    )
                color_map = {
                    atom_idx: (0.0, 0.8, 0.2)
                    for atom_idx in atoms
                }
            elif highlight_type == "delete":
                if metadata.delete_atom and metadata.byproduct_indices:
                    atoms = metadata.byproduct_indices
                    color_map = {
                        atom_idx: (1.0, 0.0, 0.0)
                        for atom_idx in atoms
                    }

            mols.extend([reactant, product])

            # Translate reactant highlight atoms to product indices using the
            # forward mapping so the same atoms are colored on both sides of
            # the reaction arrow.
            forward_map = metadata.reactant_to_product_mapping
            product_atoms = [
                forward_map[reactant_idx]
                for reactant_idx in atoms
                if reactant_idx in forward_map
            ]
            reactant_color_map = {
                atom_idx: color_map[atom_idx]
                for atom_idx in atoms
            }
            product_color_map = {
                product_idx: color_map[reactant_idx]
                for reactant_idx, product_idx in forward_map.items()
                if reactant_idx in atoms
            }

            highlight_lists.extend([atoms, product_atoms])
            highlight_colors.extend(
                [reactant_color_map, product_color_map]
            )

        if not mols:
            return None

        return Draw.MolsToGridImage(
            mols,
            legends=names,
            molsPerRow=2,
            highlightAtomLists=highlight_lists,
            highlightAtomColors=highlight_colors,
            subImgSize=(1000, 1000),
            useSVG=False,
        )
