from pathlib import Path
from datetime import datetime
now = datetime.now().strftime("%Y-%m-%d")
from AutoREACTER.reaction_preparation.lunar_client.REACTER_files_builder import REACTERFiles
from AutoREACTER.sim_setup.writers.lammps_settings import LammpsSettings


class DensificationWriter:
    def __init__(self, settings: LammpsSettings, reacter_files: REACTERFiles):
        self.settings = settings
        self.reacter_files = reacter_files

    def write_empty_box_data(self, output_dir: Path, replica: REACTERFiles):
        output_dir_densification = output_dir / "1_densification"
        half_len = replica.initial_box_length / 2.0
        lo, hi = -half_len, half_len

        lines = [
            f"#LAMMPS empty box data file - {now} Generated by AutoREACTER",
            "",
            "0 atoms",
            "0 bonds",
            "0 angles",
            "0 dihedrals",
            "0 impropers",
            "# Define the simulation box dimensions"
            "# The box is defined by its lower (xlo, ylo, zlo) and upper (xhi, yhi, zhi) limits"
            f"# This box is centered at the origin and spans from {lo:.2f} to {hi:.2f} in all directions"
            "# Box"
            "",
            f"{lo:.2f} {hi:.2f} xlo xhi",
            f"{lo:.2f} {hi:.2f} ylo yhi",
            f"{lo:.2f} {hi:.2f} zlo zhi",
            ""
        ]
        with open(output_dir_densification / "empty_box.data", 'w') as f:
            f.write("\n".join(lines))