import random
import shutil
from pathlib import Path
from datetime import datetime
from AutoREACTER.reaction_preparation.lunar_client.REACTER_files_builder import REACTERFiles
from AutoREACTER.sim_setup.writers.lammps_settings import LammpsSettings
from AutoREACTER.input_parser import Replica

now = datetime.now().strftime("%Y-%m-%d")

class DensificationWriter:
    def __init__(self, out_dir: Path, settings: LammpsSettings, reacter_files: REACTERFiles, replica: Replica, sim_name: str):
        self.settings = settings
        self.reacter_files = reacter_files
        self.erate = -0.001 
        self.timestep = 0.01 
        self.out_dir = out_dir
        self.sim_name = sim_name
        self.in_dense_file_name = self.write_lammps_densification_files(replica=replica)


    def _write_empty_box_data(self,  replica: Replica, output_dir: Path)-> None:
        
        half_len = replica.initial_box_length / 2.0
        lo, hi = -half_len, half_len

        lines = [
            f"#LAMMPS empty box data file - {now} Generated by AutoREACTER",
            "",
            "0 atoms",
            "0 bonds",
            "0 angles",
            "0 dihedrals",
            "0 impropers",
            "\n# Define the simulation box dimensions",
            "# The box is defined by its lower (xlo, ylo, zlo) and upper (xhi, yhi, zhi) limits",
            f"# This box is centered at the origin and spans from {lo:.2f} to {hi:.2f} in all directions\n",
            "# Box",
            "",
            f"{lo:.2f} {hi:.2f} xlo xhi",
            f"{lo:.2f} {hi:.2f} ylo yhi",
            f"{lo:.2f} {hi:.2f} zlo zhi",
            ""
        ]
        with open(output_dir / "empty_box.data", 'w') as f:
            f.write("\n".join(lines))
        
    def write_lammps_densification_files(self, replica: Replica) -> None:
        tag = f"{self.sim_name}_{replica.tag}"
        dens_dir = self.out_dir / "1_densification"
        dens_dir.mkdir(parents=True, exist_ok=True)

        self._write_empty_box_data(replica=replica, output_dir=dens_dir)
        
        types = self._get_force_field_types()
        s = self.settings
        rf = self.reacter_files
        total_steps, thermo_interval = self._run_calculation()
        
        lines = [
            f"# {tag} Densification Script - Generated {now}\n",
            "#------------Initialization------------",
            f"{'units':<16} {s.units}",
            f"{'dimension':<16} {s.dimension}",
            f"{'boundary':<16} {s.boundary}",
            f"{'newton':<16} on",
            "",
            "#------------Force Field------------",
            f"{'atom_style':<16} {s.atom_style}",
            f"{'bond_style':<16} {s.bond_style}",
            f"{'angle_style':<16} {s.angle_style}",
            f"{'dihedral_style':<16} {s.dihedral_style}",
            f"{'improper_style':<16} {s.improper_style}",
            f"{'special_bonds':<16} {s.special_bonds}",
            "",
            f"{'pair_style':<16} {s.pair_style}",
            f"{'kspace_style':<16} {s.kspace_style}",
            f"{'pair_modify':<16} {s.pair_modify}",
            ""
        ]

        if s.neighbor:
            lines.append(f"{'neighbor':<16} {s.neighbor}")
        if s.neigh_modify:
            lines.append(f"{'neigh_modify':<16} {s.neigh_modify}")

        lines.extend([
            "",
            "#------------Read Initial Box and Force Field------------",
            f"{'read_data':<16} empty_box.data &",
            f"{'':<16} extra/atom/types {types['atom']} &",
            f"{'':<16} extra/bond/types {types['bond']} &",
            f"{'':<16} extra/angle/types {types['angle']} &",
            f"{'':<16} extra/dihedral/types {types['dihedral']} &",
            f"{'':<16} extra/improper/types {types['improper']} &",
            f"{'':<16} extra/bond/per/atom 50 &",
            f"{'':<16} extra/angle/per/atom 50 &",
            f"{'':<16} extra/dihedral/per/atom 50 &",
            f"{'':<16} extra/improper/per/atom 50 &",
            f"{'':<16} extra/special/per/atom 50",
            "",
            f"{'read_data':<16} {rf.force_field_data.name} add append &",
            f"{'':<16} extra/bond/per/atom 50 &",
            f"{'':<16} extra/angle/per/atom 50 &",
            f"{'':<16} extra/dihedral/per/atom 50 &",
            f"{'':<16} extra/improper/per/atom 50 &",
            f"{'':<16} extra/special/per/atom 50",
        ])

        lines.append("\n#------------Define Molecule Templates------------")
        mol_ids = {}
        for i, mol in enumerate(rf.molecule_files, 1):
            m_id = f"mol_{i}"
            mol_ids[mol.id] = m_id
            lines.append(f"{'molecule':<16} {m_id} {mol.molecule_files.lmp_molecule_file.name}")

        lines.append("\n#------------Randomly Insert Molecules------------")
        for m_name, count in replica.monomer_counts.items():
            if m_name in mol_ids:
                seed = random.randint(10000, 99999)
                cmd = f"random {count} {seed} NULL overlap 2.0 maxtry 100 mol {mol_ids[m_name]} {seed}"
                lines.append(f"{'create_atoms':<16} 0 {cmd}")

        lines.extend([
            "",
            "#------------Filled box write------------",
            f"{'write_data':<16} {tag}_filled_box.data",
            "",
            f"{'minimize':<16} 0.0 1.0e-8 1000 100000",
            f"{'reset_timestep':<16} 0",
            f"{'velocity':<16} all create {replica.temperature} {random.randint(10000, 99999)} dist gaussian",
            f"{'timestep':<16} {self.timestep}",
            f"{'thermo_style':<16} custom step temp pe etotal press vol density\n",
            "#------------Densification Run------------",
            f"{'dump':<16} dump_1 all xyz 1000 {tag}_shrink.xyz",
            f"{'dump_modify':<16} dump_1 types labels",
            f"{'restart':<16} 100 {tag}_shrink_backup1.restart {tag}_shrink_backup2.restart",
            f"{'fix':<16} nvt_1 all nvt temp {replica.temperature} {replica.temperature} 100.0",
            f"{'fix':<16} fix_shrink all deform 1 x erate {self.erate} y erate {self.erate} z erate {self.erate}",
            f"{'variable':<16} my_den equal density",
            f"{'fix':<16} fix_halt all halt 1 v_my_den > {replica.density} error continue",
            f"{'thermo':<16} {thermo_interval}",
            f"{'run':<16} {total_steps}",
            "",
            f"{'unfix':<16} nvt_1",
            f"{'unfix':<16} fix_shrink",
            f"{'unfix':<16} fix_halt",
            f"{'undump':<16} dump_1",
            f"{'write_data':<16} {tag}_shrinked_box.data"
        ])

        in_dest_location = dens_dir / f"in.{tag}_densification"
        with open(in_dest_location, 'w') as f:
            f.write("\n".join(lines))
        
        self._copy_required_files(dest_dir=dens_dir)

        return in_dest_location.name

    def _get_force_field_types(self) -> dict:
        data_file = self.reacter_files.force_field_data
        if not data_file.exists():
            raise FileNotFoundError(f"Force field data file not found: {data_file}")

        type_counts = {
            "atom": None,
            "bond": None,
            "angle": None,
            "dihedral": None,
            "improper": 0
        }

        with open(data_file, 'r') as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                parts = line.split()
                if len(parts) >= 3 and parts[2] == "types":
                    type_key = parts[1]
                    if type_key in type_counts:
                        type_counts[type_key] = int(parts[0])
                
                if any(header in line for header in ["Atoms", "Masses", "Bonds"]):
                    break

        required_keys = ["atom", "bond", "angle", "dihedral"]
        for key in required_keys:
            if type_counts[key] is None:
                raise ValueError(f"Required LAMMPS header '{key} types' not found in {data_file}")

        return type_counts
    
    def _run_calculation(self) -> int:
        # We start at 1/4 density, so target volume is 0.25 of initial
        # L_target / L_initial = cuberoot(0.25)
        l_ratio = (0.25) ** (1/3)
        
        # Deformation: L = L0(1 + erate * time)
        # time = (l_ratio - 1) / erate
        total_time = (l_ratio - 1) / self.erate
        steps_needed = total_time / self.timestep
        factor = 1.25  # Add 25% buffer to ensure fix halt catches it
        if steps_needed <= 0:
            raise ValueError(f"Calculated negative steps needed for densification: {steps_needed}. Check erate and timestep values.")
        if steps_needed < 10000:
            round_steps = round(steps_needed * factor, -3)  # Round to nearest 10,000
            thermo_interval = 1000
        elif steps_needed > 1000:
            round_steps = round(steps_needed * factor, -3)  # Round to nearest 1000
            thermo_interval = 100
        elif steps_needed > 100:
            round_steps = round(steps_needed * factor, -2) # Round to nearest 100
            thermo_interval = 10
        elif steps_needed > 10:
            round_steps = round(steps_needed * factor, -1) # Round to nearest 10
            thermo_interval = 1
        else:
            round_steps = round(steps_needed * factor) # Round to nearest integer
            thermo_interval = 1
        return int(round_steps), thermo_interval

    def _copy_required_files(self, dest_dir: Path):
        rf = self.reacter_files
        
        if rf.force_field_data.exists():
            shutil.copy2(rf.force_field_data, dest_dir / rf.force_field_data.name)
        
        for mol in rf.molecule_files:
            if mol.molecule_files and mol.molecule_files.lmp_molecule_file.exists():
                src = mol.molecule_files.lmp_molecule_file
                shutil.copy2(src, dest_dir / src.name)
    